In [1]:
%load_ext autoreload
%autoreload 2


#%run ./src/run.py --help


In [3]:
import subprocess

# Define the parameters
experiment = "smnist"
approach = "gvcl"
reg_type = "re_g"
dof = 50
seed = [14,33,56,78,91]

# Loop over the seeds and run the experiment
for sd in seed:
    print(f"Running experiment with seed {sd}")
    subprocess.run([
        "python", "./src/run.py",
        "--experiment", experiment,
        "--approach", approach,
        "--seed", str(sd),
        "--use-sweep", str(True),
        "--reg_type", reg_type
    ])

Running experiment with seed 14


wandb: Currently logged in as: naima-elosegui (nagiu). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.3
wandb: Run data is saved locally in /home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/wandb/run-20250130_122212-lr7arzo1
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run colorful-blaze-3435
wandb: ⭐️ View project at https://wandb.ai/nagiu/curvy-cl
wandb: 🚀 View run at https://wandb.ai/nagiu/curvy-cl/runs/lr7arzo1


Arguments =
	sweep_name: None
	seed: 14
	experiment: smnist
	approach: gvcl
	reg_type: re_g
	q: 1.01
	v: 1
	output: ./res/smnist/gvcl_re_g_14.txt
	nepochs: None
	lr: -1
	parameter: 
	ntasks: -1
	context: None
	momentum: 0.9
	weight_decay: 0.0
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
	optimizer: sgd
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([0, 0, 1,  ..., 1, 1, 0])
tensor([1, 1, 1,  ..., 0, 0, 0])
tensor([0, 0, 1,  ..., 1, 1, 0])
tensor([0, 1, 0,  ..., 1, 0, 1])
tensor([0, 0, 0,  ..., 1, 1, 0])
tensor([0, 1, 0,  ..., 1, 1, 0])
tensor([1, 0, 1,  ..., 1, 1, 1])
tensor([0, 0, 1,  ..., 0, 0, 0])
tensor([0, 0, 0,  ..., 1, 1, 1])
tensor([0, 0, 0,  ..., 0, 0, 0])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:     avg_accuracy ▁▂▃▃▄▅▆▆▇█
wandb:       class_loss ▁▁▁▁█▂▂▂▅▁▁▁▁▃▂▂▂▂▂▂▂▄▂▂▂▄▃▂▂▂▂▂▂▂▂▆▃▂▂▂
wandb:            epoch ▁▁▁▂▂▂▂▂▂▂▃▃▃▃▄▄▄▄▄▄▄▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇▇▇██
wandb:          kl_loss ██▇▇▇▆▃▂▂▂▃▂▂▁▁▁▁▂▂▁▁▃▂▁▁▂▂▁▁▁▁▁▄▁▁▁▁▄▁▁
wandb:               lr ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:  test_acc_task_0 ███▆▄▂▇▁▆▆
wandb:  test_acc_task_1 ██▇▆█▆▄▄▁
wandb:  test_acc_task_2 ████▇▃▄▁
wandb:  test_acc_task_3 █▅▅▄▅▁▁
wandb:  test_acc_task_4 ██▁▆▃▄
wandb:  test_acc_task_5 ▄█▂▁▆
wandb:  test_acc_task_6 █▄▁▄
wandb:  test_acc_task_7 █▁▃
wandb:  test_acc_task_8 ▁█
wandb:  test_acc_task_9 ▁
wandb: test_loss_task_0 ▁▁▁▁▁▁▁▁▁▁
wandb: test_loss_task_1 ▁▁▁▁▁▁▁▁▁
wandb: test_loss_task_2 ▁▁▁▁▁▁▁▁
wandb: test_loss_task_3 ▁▁▁▁▁▁▁
wandb: test_loss_task_4 ▁▁▁▁▁▁
wandb: test_loss_task_5 ▁▁▁▁▁
wandb: test_loss_task_6 ▁▁▁▁
wandb: test_loss_task_7 ▁▁▁
wandb: test_loss_task_8 ▁▁
wandb:

****************************************************************************************************
training for 11 epochs
Total number of steps per task 7: 1856
| Epoch   1, time= 18.2ms| Train: class_loss=0.001  kl_loss=0.010 total_loss=0.011, acc= 96.7% |
| Epoch   2, time= 18.0ms| Train: class_loss=0.001  kl_loss=0.004 total_loss=0.004, acc= 98.8% |
| Epoch   3, time= 18.3ms| Train: class_loss=0.001  kl_loss=0.003 total_loss=0.003, acc= 99.1% |
| Epoch   4, time= 18.2ms| Train: class_loss=0.000  kl_loss=0.002 total_loss=0.002, acc= 99.4% |
| Epoch   5, time= 18.2ms| Train: class_loss=0.000  kl_loss=0.002 total_loss=0.002, acc= 99.5% |
| Epoch   6, time= 18.3ms| Train: class_loss=0.000  kl_loss=0.001 total_loss=0.002, acc= 99.5% |
| Epoch   7, time= 18.3ms| Train: class_loss=0.000  kl_loss=0.001 total_loss=0.001, acc= 99.5% |
| Epoch   8, time= 18.9ms| Train: class_loss=0.000  kl_loss=0.001 total_loss=0.001, acc= 99.5% |
| Epoch   9, time= 18.6ms| Train: class_loss=0.000  kl_loss=0

wandb: Currently logged in as: naima-elosegui (nagiu). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.3
wandb: Run data is saved locally in /home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/wandb/run-20250130_122840-f2s09ot7
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run devout-armadillo-3436
wandb: ⭐️ View project at https://wandb.ai/nagiu/curvy-cl
wandb: 🚀 View run at https://wandb.ai/nagiu/curvy-cl/runs/f2s09ot7


Arguments =
	sweep_name: None
	seed: 33
	experiment: smnist
	approach: gvcl
	reg_type: re_g
	q: 1.01
	v: 1
	output: ./res/smnist/gvcl_re_g_33.txt
	nepochs: None
	lr: -1
	parameter: 
	ntasks: -1
	context: None
	momentum: 0.9
	weight_decay: 0.0
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
	optimizer: sgd
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([1, 0, 0,  ..., 1, 0, 0])
tensor([1, 0, 0,  ..., 1, 0, 0])
tensor([1, 0, 0,  ..., 1, 0, 0])
tensor([1, 1, 1,  ..., 0, 1, 0])
tensor([1, 1, 0,  ..., 1, 1, 1])
tensor([0, 1, 0,  ..., 1, 1, 1])
tensor([0, 1, 1,  ..., 0, 1, 1])
tensor([0, 1, 0,  ..., 1, 1, 0])
tensor([1, 0, 0,  ..., 1, 0, 0])
tensor([0, 0, 1,  ..., 1, 1, 1])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:     avg_accuracy ▁▂▃▃▄▅▆▆▇█
wandb:       class_loss ▂▁▁▁▁▂▂▂▂▅▁▁▁▁▁█▄▃▂▂▂█▄▃▂▂▃▃▃▂▃▂▂▂▂▂▂▂▂▂
wandb:            epoch ▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▄▅▅▅▅▅▆▆▆▇▇▇▇▇▇▇▇▇███
wandb:          kl_loss ███▇▆▂▂▂▂▂▁▁▂▃▂▁▁▁▃▂▁▁▁▂▂▁▁▁▄▂▁▁▁▄▁▁▁▁▁▁
wandb:               lr ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:  test_acc_task_0 ████▇▆▆▁▆▆
wandb:  test_acc_task_1 ███▄▅▄▄▃▁
wandb:  test_acc_task_2 █▇▅▃▆▆▄▁
wandb:  test_acc_task_3 ██▇██▇▁
wandb:  test_acc_task_4 █▇▇▃▁▃
wandb:  test_acc_task_5 █▆▃▂▁
wandb:  test_acc_task_6 █▆▄▁
wandb:  test_acc_task_7 █▇▁
wandb:  test_acc_task_8 ▁█
wandb:  test_acc_task_9 ▁
wandb: test_loss_task_0 ▁▁▁▁▁▁▁▁▁▁
wandb: test_loss_task_1 ▁▁▁▁▁▁▁▁▁
wandb: test_loss_task_2 ▁▁▁▁▁▁▁▁
wandb: test_loss_task_3 ▁▁▁▁▁▁▁
wandb: test_loss_task_4 ▁▁▁▁▁▁
wandb: test_loss_task_5 ▁▁▁▁▁
wandb: test_loss_task_6 ▁▁▁▁
wandb: test_loss_task_7 ▁▁▁
wandb: test_loss_task_8 ▁▁
wandb:

****************************************************************************************************
training for 11 epochs
Total number of steps per task 7: 1856
| Epoch   1, time= 16.0ms| Train: class_loss=0.001  kl_loss=0.010 total_loss=0.012, acc= 96.9% |
| Epoch   2, time= 17.4ms| Train: class_loss=0.001  kl_loss=0.004 total_loss=0.005, acc= 98.7% |
| Epoch   3, time= 15.8ms| Train: class_loss=0.001  kl_loss=0.003 total_loss=0.003, acc= 99.0% |
| Epoch   4, time= 17.6ms| Train: class_loss=0.000  kl_loss=0.002 total_loss=0.003, acc= 99.2% |
| Epoch   5, time= 14.9ms| Train: class_loss=0.000  kl_loss=0.002 total_loss=0.002, acc= 99.3% |
| Epoch   6, time= 12.5ms| Train: class_loss=0.000  kl_loss=0.001 total_loss=0.002, acc= 99.5% |
| Epoch   7, time= 12.5ms| Train: class_loss=0.000  kl_loss=0.001 total_loss=0.001, acc= 99.5% |
| Epoch   8, time= 12.5ms| Train: class_loss=0.000  kl_loss=0.001 total_loss=0.001, acc= 99.4% |
| Epoch   9, time= 12.5ms| Train: class_loss=0.000  kl_loss=0

wandb: Currently logged in as: naima-elosegui (nagiu). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.3
wandb: Run data is saved locally in /home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/wandb/run-20250130_123458-3kblqt8n
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run charmed-planet-3442
wandb: ⭐️ View project at https://wandb.ai/nagiu/curvy-cl
wandb: 🚀 View run at https://wandb.ai/nagiu/curvy-cl/runs/3kblqt8n


Arguments =
	sweep_name: None
	seed: 56
	experiment: smnist
	approach: gvcl
	reg_type: re_g
	q: 1.01
	v: 1
	output: ./res/smnist/gvcl_re_g_56.txt
	nepochs: None
	lr: -1
	parameter: 
	ntasks: -1
	context: None
	momentum: 0.9
	weight_decay: 0.0
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
	optimizer: sgd
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([1, 1, 1,  ..., 1, 0, 1])
tensor([1, 0, 1,  ..., 0, 0, 0])
tensor([1, 0, 0,  ..., 0, 0, 1])
tensor([0, 1, 0,  ..., 1, 0, 1])
tensor([0, 0, 0,  ..., 0, 0, 1])
tensor([1, 0, 0,  ..., 1, 0, 0])
tensor([1, 0, 0,  ..., 0, 1, 0])
tensor([0, 1, 1,  ..., 1, 1, 0])
tensor([0, 1, 1,  ..., 0, 0, 1])
tensor([1, 1, 1,  ..., 1, 0, 0])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:     avg_accuracy ▁▂▃▃▄▅▆▆▇█
wandb:       class_loss ▄▁▁▁▁█▄▃▂▂▂▁▁▁▁▅▄▃▅▃▃▃▃▂▆▅▆▆▆▄▇▅▄▃▃▅▄▅▃▃
wandb:            epoch ▁▁▁▂▂▂▂▃▃▃▃▄▄▄▄▅▅▅▅▅▅▅▅▅▆▆▆▆▇▇▇▇▇▇▇█████
wandb:          kl_loss ███▇▆▃▂▂▂▂▂▁▁▂▁▁▁▁▁▁▁▁▁▁▁▂▂▁▁▁▁▁▂▁▁▁▁▁▁▁
wandb:               lr ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:  test_acc_task_0 ▇███▇▆▆▅▁▄
wandb:  test_acc_task_1 ██▇▁▅▅▂▅▅
wandb:  test_acc_task_2 ███▇▆▆▄▁
wandb:  test_acc_task_3 ▇▇▇██▅▁
wandb:  test_acc_task_4 ▇██▇▅▁
wandb:  test_acc_task_5 ▇▆█▇▁
wandb:  test_acc_task_6 █▃▂▁
wandb:  test_acc_task_7 ▄▁█
wandb:  test_acc_task_8 ▁█
wandb:  test_acc_task_9 ▁
wandb: test_loss_task_0 ▁▁▁▁▁▁▁▁▁▁
wandb: test_loss_task_1 ▁▁▁▁▁▁▁▁▁
wandb: test_loss_task_2 ▁▁▁▁▁▁▁▁
wandb: test_loss_task_3 ▁▁▁▁▁▁▁
wandb: test_loss_task_4 ▁▁▁▁▁▁
wandb: test_loss_task_5 ▁▁▁▁▁
wandb: test_loss_task_6 ▁▁▁▁
wandb: test_loss_task_7 ▁▁▁
wandb: test_loss_task_8 ▁▁
wandb:

****************************************************************************************************
training for 11 epochs
Total number of steps per task 7: 1856
| Epoch   1, time= 17.7ms| Train: class_loss=0.001  kl_loss=0.010 total_loss=0.012, acc= 97.0% |
| Epoch   2, time= 18.2ms| Train: class_loss=0.001  kl_loss=0.004 total_loss=0.004, acc= 98.6% |
| Epoch   3, time= 18.2ms| Train: class_loss=0.001  kl_loss=0.003 total_loss=0.003, acc= 99.0% |
| Epoch   4, time= 17.9ms| Train: class_loss=0.000  kl_loss=0.002 total_loss=0.003, acc= 99.2% |
| Epoch   5, time= 18.2ms| Train: class_loss=0.000  kl_loss=0.002 total_loss=0.002, acc= 99.4% |
| Epoch   6, time= 18.4ms| Train: class_loss=0.000  kl_loss=0.001 total_loss=0.002, acc= 99.4% |
| Epoch   7, time= 18.3ms| Train: class_loss=0.000  kl_loss=0.001 total_loss=0.001, acc= 99.5% |
| Epoch   8, time= 18.1ms| Train: class_loss=0.000  kl_loss=0.001 total_loss=0.001, acc= 99.5% |
| Epoch   9, time= 17.6ms| Train: class_loss=0.000  kl_loss=0

wandb: Currently logged in as: naima-elosegui (nagiu). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.3
wandb: Run data is saved locally in /home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/wandb/run-20250130_124121-i5stdajo
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run cerulean-pyramid-3444
wandb: ⭐️ View project at https://wandb.ai/nagiu/curvy-cl
wandb: 🚀 View run at https://wandb.ai/nagiu/curvy-cl/runs/i5stdajo


Arguments =
	sweep_name: None
	seed: 78
	experiment: smnist
	approach: gvcl
	reg_type: re_g
	q: 1.01
	v: 1
	output: ./res/smnist/gvcl_re_g_78.txt
	nepochs: None
	lr: -1
	parameter: 
	ntasks: -1
	context: None
	momentum: 0.9
	weight_decay: 0.0
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
	optimizer: sgd
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([0, 0, 1,  ..., 0, 1, 1])
tensor([1, 1, 1,  ..., 0, 1, 0])
tensor([0, 1, 0,  ..., 0, 1, 0])
tensor([0, 0, 1,  ..., 0, 0, 1])
tensor([0, 0, 1,  ..., 0, 1, 1])
tensor([0, 1, 1,  ..., 0, 1, 1])
tensor([1, 0, 1,  ..., 0, 0, 1])
tensor([1, 0, 0,  ..., 0, 0, 0])
tensor([0, 0, 0,  ..., 1, 1, 1])
tensor([1, 0, 1,  ..., 1, 0, 1])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:     avg_accuracy ▁▂▃▃▄▅▆▆▇█
wandb:       class_loss ▄▁▁▁▁▆▄▃▃▂▂▂▂▂▄▁▂▁▁▅▃▃█▄▃▃▆▄▃▆▅▄▃▃▃▄▃▃▃▂
wandb:            epoch ▁▁▁▁▁▁▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▆▆▆▆▆▆▆▆▆▇▇▇▇▇▇████
wandb:          kl_loss ██▇▇▆▂▂▂▂▂▂▁▁▃▂▁▁▁▂▂▁▂▁▁▁▁▁▄▁▁▁▁▁▁▁▄▁▁▁▁
wandb:               lr ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:  test_acc_task_0 ▇█▇▁▄▁▅▇▇█
wandb:  test_acc_task_1 █▇▆▆▇▅▃▂▁
wandb:  test_acc_task_2 █▇▆▃▁▆▆█
wandb:  test_acc_task_3 ▁▅██▁▁▁
wandb:  test_acc_task_4 ██▆█▁▁
wandb:  test_acc_task_5 ▇█▃▄▁
wandb:  test_acc_task_6 █▆▆▁
wandb:  test_acc_task_7 ▁█▃
wandb:  test_acc_task_8 █▁
wandb:  test_acc_task_9 ▁
wandb: test_loss_task_0 ▁▁▁▁▁▁▁▁▁▁
wandb: test_loss_task_1 ▁▁▁▁▁▁▁▁▁
wandb: test_loss_task_2 ▁▁▁▁▁▁▁▁
wandb: test_loss_task_3 ▁▁▁▁▁▁▁
wandb: test_loss_task_4 ▁▁▁▁▁▁
wandb: test_loss_task_5 ▁▁▁▁▁
wandb: test_loss_task_6 ▁▁▁▁
wandb: test_loss_task_7 ▁▁▁
wandb: test_loss_task_8 ▁▁
wandb:

****************************************************************************************************
training for 11 epochs
Total number of steps per task 7: 1856
| Epoch   1, time= 15.9ms| Train: class_loss=0.001  kl_loss=0.010 total_loss=0.011, acc= 96.8% |
| Epoch   2, time= 18.3ms| Train: class_loss=0.001  kl_loss=0.004 total_loss=0.004, acc= 98.7% |
| Epoch   3, time= 18.4ms| Train: class_loss=0.000  kl_loss=0.003 total_loss=0.003, acc= 99.2% |
| Epoch   4, time= 14.8ms| Train: class_loss=0.000  kl_loss=0.002 total_loss=0.002, acc= 99.3% |
| Epoch   5, time= 12.6ms| Train: class_loss=0.000  kl_loss=0.002 total_loss=0.002, acc= 99.4% |
| Epoch   6, time= 12.6ms| Train: class_loss=0.000  kl_loss=0.001 total_loss=0.002, acc= 99.4% |
| Epoch   7, time= 16.5ms| Train: class_loss=0.000  kl_loss=0.001 total_loss=0.002, acc= 99.4% |
| Epoch   8, time= 19.2ms| Train: class_loss=0.000  kl_loss=0.001 total_loss=0.001, acc= 99.5% |
| Epoch   9, time= 18.9ms| Train: class_loss=0.000  kl_loss=0

wandb: Currently logged in as: naima-elosegui (nagiu). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.3
wandb: Run data is saved locally in /home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/wandb/run-20250130_124753-phiczt88
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run happy-river-3448
wandb: ⭐️ View project at https://wandb.ai/nagiu/curvy-cl
wandb: 🚀 View run at https://wandb.ai/nagiu/curvy-cl/runs/phiczt88


Arguments =
	sweep_name: None
	seed: 91
	experiment: smnist
	approach: gvcl
	reg_type: re_g
	q: 1.01
	v: 1
	output: ./res/smnist/gvcl_re_g_91.txt
	nepochs: None
	lr: -1
	parameter: 
	ntasks: -1
	context: None
	momentum: 0.9
	weight_decay: 0.0
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
	optimizer: sgd
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([0, 1, 0,  ..., 0, 0, 0])
tensor([1, 1, 0,  ..., 1, 1, 0])
tensor([1, 1, 0,  ..., 1, 1, 0])
tensor([1, 1, 1,  ..., 0, 0, 1])
tensor([1, 0, 1,  ..., 1, 1, 0])
tensor([1, 1, 0,  ..., 1, 1, 1])
tensor([1, 1, 1,  ..., 0, 1, 0])
tensor([0, 0, 1,  ..., 1, 0, 0])
tensor([0, 0, 0,  ..., 0, 1, 1])
tensor([1, 1, 0,  ..., 1, 0, 0])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:     avg_accuracy ▁▂▃▃▄▅▆▆▇█
wandb:       class_loss ▃▁▁▁▁▁▁▃▃▂▁▁▃▁▁▃▂▂▂▂▅▂▂▂▂█▄▃▃▂▂▃▂▇▂▇▂▂▂▂
wandb:            epoch ▁▁▂▂▂▂▂▃▃▃▃▄▄▄▄▄▄▄▄▄▅▅▅▆▆▆▆▇▇▇▇▇▇▇▇▇▇▇██
wandb:          kl_loss ██▆▃▂▁▂▂▁▁▂▁▃▂▂▁▁▁▁▁▁▃▂▂▁▁▁▁▁▁▁▄▁▁▁▁▄▂▁▁
wandb:               lr ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:  test_acc_task_0 ▇██▆▂▃▁▃▄▅
wandb:  test_acc_task_1 ███▆▆▅▁▄▃
wandb:  test_acc_task_2 ▇████▆▃▁
wandb:  test_acc_task_3 ████▁▆▁
wandb:  test_acc_task_4 ██▆▇▁▁
wandb:  test_acc_task_5 ██▂▆▁
wandb:  test_acc_task_6 █▄▃▁
wandb:  test_acc_task_7 █▁▄
wandb:  test_acc_task_8 ▁▁
wandb:  test_acc_task_9 ▁
wandb: test_loss_task_0 ▁▁▁▁▁▁▁▁▁▁
wandb: test_loss_task_1 ▁▁▁▁▁▁▁▁▁
wandb: test_loss_task_2 ▁▁▁▁▁▁▁▁
wandb: test_loss_task_3 ▁▁▁▁▁▁▁
wandb: test_loss_task_4 ▁▁▁▁▁▁
wandb: test_loss_task_5 ▁▁▁▁▁
wandb: test_loss_task_6 ▁▁▁▁
wandb: test_loss_task_7 ▁▁▁
wandb: test_loss_task_8 ▁▁
wandb:

****************************************************************************************************
training for 11 epochs
Total number of steps per task 7: 1856
| Epoch   1, time= 18.4ms| Train: class_loss=0.001  kl_loss=0.010 total_loss=0.012, acc= 96.9% |
| Epoch   2, time= 18.3ms| Train: class_loss=0.001  kl_loss=0.004 total_loss=0.004, acc= 98.7% |
| Epoch   3, time= 18.3ms| Train: class_loss=0.000  kl_loss=0.003 total_loss=0.003, acc= 99.1% |
| Epoch   4, time= 17.9ms| Train: class_loss=0.000  kl_loss=0.002 total_loss=0.003, acc= 99.2% |
| Epoch   5, time= 18.1ms| Train: class_loss=0.000  kl_loss=0.002 total_loss=0.002, acc= 99.5% |
| Epoch   6, time= 18.0ms| Train: class_loss=0.000  kl_loss=0.001 total_loss=0.002, acc= 99.4% |
| Epoch   7, time= 18.2ms| Train: class_loss=0.000  kl_loss=0.001 total_loss=0.001, acc= 99.6% |
| Epoch   8, time= 18.1ms| Train: class_loss=0.000  kl_loss=0.001 total_loss=0.001, acc= 99.6% |
| Epoch   9, time= 18.3ms| Train: class_loss=0.000  kl_loss=0

## Run experiments

In [2]:
import subprocess

# Define the parameters
experiment = "cifar"
approach = "gvcl"
reg_type = "kl_g"
seed = [98,93] #missing 98 and 93

# Loop over the seeds and run the experiment
for sd in seed:
    print(f"Running experiment with seed {sd}")
    subprocess.run([
        "python", "./src/run.py",
        "--experiment", experiment,
        "--approach", approach,
        "--seed", str(sd),
        "--use-sweep", str(True),
        "--reg_type", reg_type
    ])

Running experiment with seed 98


/home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/src/dataloaders/cifar.py:74: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data[i][s]['x']=torch.load(os.path.join(os.path.ex

Arguments =
	sweep_name: None
	seed: 98
	experiment: cifar
	approach: gvcl
	reg_type: kl_g
	q: 1.01
	v: 1
	output: ./res/cifar_gvcl_kl_g_98.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
	optimizer: sgd
approach VCL True
Load data...
Task order = [0, 1, 2, 3, 4, 5]
Input size = [3, 32, 32] 
Task info = [(0, 10), (1, 10), (2, 10), (3, 10), (4, 10), (5, 10)]
Inits...
----------------------------------------------------------------------------------------------------
Net(
  (conv_layers): ModuleList(
    (0): MFConvLayer(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): MFConvLayer(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (2): MFConvLayer(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): MFConvLayer(64, 64, kernel_size=(3, 3), stride=(

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:     avg_accuracy ▁▂▄▅▇█
wandb:       class_loss ▂█▂▁▁▁▂▂▁▁▁▁▁▁▁█▂▂▁▁▁▁▁▁▁▂▂▂▁▁▂▁▁▁▁▁▁▁▁▁
wandb:            epoch ▁▁▁▂▂▂▂▂▃▃▃▄▄▄▄▅▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇▇▇▇▇███
wandb:          kl_loss ▃▃▃▃▂▂▂▂▂▃▂▂▂█▂▂▂▂▂▂▃▂▂▂▂▂▁▁▁▁▂▁▁▁▁▁▁▁▁▁
wandb:               lr ████▆▄▄▃▃▃▂▁▁▁█▇▆▅▄▁▅▄▃▃▁█▇▇▆▅▃█▇▅▄▄▃▂▁▁
wandb:  test_acc_task_0 █▄▄▃▂▁
wandb:  test_acc_task_1 █▃▁▂▁
wandb:  test_acc_task_2 █▂▁▄
wandb:  test_acc_task_3 █▂▁
wandb:  test_acc_task_4 █▁
wandb:  test_acc_task_5 ▁
wandb: test_loss_task_0 ▁▁▁▁▁▁
wandb: test_loss_task_1 ▁▁▁▁▁
wandb: test_loss_task_2 ▁▁▁▁
wandb: test_loss_task_3 ▁▁▁
wandb: test_loss_task_4 ▁▁
wandb: test_loss_task_5 ▁
wandb:       total_loss █▄▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:        train_acc ▁▄▆▆▆█████▆▆▇▇▆▇▇█████▆▆▆▇▇█▄▆▇▇▇▇▇█████
wandb: 
wandb: Run summary:
wandb:     avg_accuracy 0.72028
wandb:       class_loss 0.00485
wandb:            epoch 1020
w

| Epoch 192, time= 50.7ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 95.9% |
| Epoch 193, time= 50.6ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.2% |
| Epoch 194, time= 51.0ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 96.2% |
| Epoch 195, time= 50.6ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.2% |
| Epoch 196, time= 50.8ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.2% |
| Epoch 197, time= 50.6ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 96.0% |
| Epoch 198, time= 50.8ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.3% |
| Epoch 199, time= 50.7ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 96.4% |
| Epoch 200, time= 50.7ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 96.2% |
----------------------------------------------------------------------------------------------------
>>> Test on task  0 - cifa

/home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/src/dataloaders/cifar.py:74: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data[i][s]['x']=torch.load(os.path.join(os.path.ex

Arguments =
	sweep_name: None
	seed: 93
	experiment: cifar
	approach: gvcl
	reg_type: kl_g
	q: 1.01
	v: 1
	output: ./res/cifar_gvcl_kl_g_93.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
	optimizer: sgd
approach VCL True
Load data...
Task order = [0, 1, 2, 3, 4, 5]
Input size = [3, 32, 32] 
Task info = [(0, 10), (1, 10), (2, 10), (3, 10), (4, 10), (5, 10)]
Inits...
----------------------------------------------------------------------------------------------------
Net(
  (conv_layers): ModuleList(
    (0): MFConvLayer(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): MFConvLayer(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (2): MFConvLayer(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): MFConvLayer(64, 64, kernel_size=(3, 3), stride=(

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:     avg_accuracy ▁▂▄▅▇█
wandb:       class_loss ▂▂▂▂▁▁▁▁█▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄▂▂▂▂▁▁▁▁
wandb:            epoch ▁▁▁▁▁▂▂▂▂▃▃▄▄▄▄▅▅▅▅▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇████
wandb:          kl_loss █▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁
wandb:               lr ▅▇▇▆▅▂▁▁▁▁▇▆▄▃▂▁▁▁▁█▆▆▆▆▅███▇▇▆▅▂▁▁▆▅▅▄▁
wandb:  test_acc_task_0 █▂▄▂▂▁
wandb:  test_acc_task_1 █▃▁▁▁
wandb:  test_acc_task_2 █▁▄▃
wandb:  test_acc_task_3 █▃▁
wandb:  test_acc_task_4 █▁
wandb:  test_acc_task_5 ▁
wandb: test_loss_task_0 ▁▁▁▁▁▁
wandb: test_loss_task_1 ▁▁▁▁▁
wandb: test_loss_task_2 ▁▁▁▁
wandb: test_loss_task_3 ▁▁▁
wandb: test_loss_task_4 ▁▁
wandb: test_loss_task_5 ▁
wandb:       total_loss ▃▂▂▂▂▂▂▂▂▂▄▂▂▂▂▂▂▂▃▂▂▂▂▂▁▁▁▁▂▂▁▁▁█▁▁▁▁▁▁
wandb:        train_acc ▆▇▇▇██▇▇█████▆▇████████▁▇▇▇▇██████▇█████
wandb: 
wandb: Run summary:
wandb:     avg_accuracy 0.72825
wandb:       class_loss 0.00488
wandb:            epoch 1020
w

| Epoch 192, time= 50.5ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 96.1% |
| Epoch 193, time= 50.5ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 96.3% |
| Epoch 194, time= 50.5ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 96.0% |
| Epoch 195, time= 50.5ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 96.2% |
| Epoch 196, time= 50.5ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 96.0% |
| Epoch 197, time= 50.5ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 96.2% |
| Epoch 198, time= 50.5ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 96.0% |
| Epoch 199, time= 50.5ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 96.0% |
| Epoch 200, time= 50.5ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 96.0% |
----------------------------------------------------------------------------------------------------
>>> Test on task  0 - cifa

In [1]:
import subprocess

# Define the parameters
experiment = "cifar"
approach = "gvcl"
reg_type = "re_g"
seed = [54,76,98,93] #32 done already seeds:[32,54,76,98,93]

# Loop over the seeds and run the experiment
for sd in seed:
    print(f"Running experiment with seed {sd}")
    subprocess.run([
        "python", "./src/run.py",
        "--experiment", experiment,
        "--approach", approach,
        "--seed", str(sd),
        "--use-sweep", str(True),
        "--reg_type", reg_type
    ])

Running experiment with seed 54


/home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/src/dataloaders/cifar.py:74: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data[i][s]['x']=torch.load(os.path.join(os.path.ex

Arguments =
	sweep_name: None
	seed: 54
	experiment: cifar
	approach: gvcl
	reg_type: re_g
	q: 1.01
	v: 1
	output: ./res/cifar_gvcl_re_g_54.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
	optimizer: sgd
approach VCL True
Load data...
Task order = [0, 1, 2, 3, 4, 5]
Input size = [3, 32, 32] 
Task info = [(0, 10), (1, 10), (2, 10), (3, 10), (4, 10), (5, 10)]
Inits...
----------------------------------------------------------------------------------------------------
Net(
  (conv_layers): ModuleList(
    (0): MFConvLayer(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): MFConvLayer(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (2): MFConvLayer(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): MFConvLayer(64, 64, kernel_size=(3, 3), stride=(

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:     avg_accuracy ▁▂▄▅▇█
wandb:       class_loss █▆▇▇▆▆▆▆▅▆▅▇▆▆▆▅▅▅▄▄▃▃▂██▇▆▆▅▄▄▃▃▃▃▃▂▂▁▁
wandb:            epoch ▁▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▅▅▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇██
wandb:          kl_loss █▃▃▂▂▂▂▂▃▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▃▂▂▂▁▁▁▁▂▁▁▁▁▁▁
wandb:               lr ███▇▆▂▂▁██▅▄▄▃▃▁▁▁██▅▄▃▂▁▁▁▁▁█▇▄▃▂▁████▁
wandb:  test_acc_task_0 █▂▄▂▃▁
wandb:  test_acc_task_1 █▃▂▁▁
wandb:  test_acc_task_2 █▁▄▄
wandb:  test_acc_task_3 █▂▁
wandb:  test_acc_task_4 █▁
wandb:  test_acc_task_5 ▁
wandb: test_loss_task_0 ▁▁▁▁▁▁
wandb: test_loss_task_1 ▁▁▁▁▁
wandb: test_loss_task_2 ▁▁▁▁
wandb: test_loss_task_3 ▁▁▁
wandb: test_loss_task_4 ▁▁
wandb: test_loss_task_5 ▁
wandb:       total_loss █▆▄▄▄▄▄▃▃▆▄▃▃▃▃▇▆▃▃▂▂▂▂▂▇▃▂▂▂▂▂▂▂▂▅▄▃▃▁▁
wandb:        train_acc ▁▂▃▄▄▄▄▅▅▅▆▂▄▄▄▅▅▅▅▅▅▆▆▆▆▇█▃▃▃▄▄▄▄▅▇▇███
wandb: 
wandb: Run summary:
wandb:     avg_accuracy 0.70902
wandb:       class_loss 0.01106
wandb:            epoch 1020
w

| Epoch 192, time= 52.5ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 81.8% |
| Epoch 193, time= 52.5ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 81.9% |
| Epoch 194, time= 52.4ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 81.4% |
| Epoch 195, time= 52.4ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 81.9% |
| Epoch 196, time= 52.5ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 81.9% |
| Epoch 197, time= 52.4ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 82.1% |
| Epoch 198, time= 52.4ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 81.5% |
| Epoch 199, time= 52.4ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 82.2% |
| Epoch 200, time= 52.4ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 82.1% |
----------------------------------------------------------------------------------------------------
>>> Test on task  0 - cifa

/home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/src/dataloaders/cifar.py:74: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data[i][s]['x']=torch.load(os.path.join(os.path.ex

Arguments =
	sweep_name: None
	seed: 76
	experiment: cifar
	approach: gvcl
	reg_type: re_g
	q: 1.01
	v: 1
	output: ./res/cifar_gvcl_re_g_76.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
	optimizer: sgd
approach VCL True
Load data...
Task order = [0, 1, 2, 3, 4, 5]
Input size = [3, 32, 32] 
Task info = [(0, 10), (1, 10), (2, 10), (3, 10), (4, 10), (5, 10)]
Inits...
----------------------------------------------------------------------------------------------------
Net(
  (conv_layers): ModuleList(
    (0): MFConvLayer(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): MFConvLayer(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (2): MFConvLayer(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): MFConvLayer(64, 64, kernel_size=(3, 3), stride=(

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:     avg_accuracy ▁▂▄▅▇█
wandb:       class_loss ▁▁█▄▄▄▄▄▄▄▃▃▄▃▃▃▃▃▃▃▄▄▄▄▄▄▄▄▄▄▃▃▃▃▃▃▂▂▂▂
wandb:            epoch ▁▁▁▁▁▂▂▂▂▂▂▂▃▃▃▄▄▄▄▄▄▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇████
wandb:          kl_loss ███▃▂▂▂▂▂▂▂▂▃▂▂▂▂▂▂▂▇▃▂▁▁▁▁▁▁▂▁▁▁▁▁▂▁▁▁▁
wandb:               lr ▁▇▇▅▅▁▁▁█▇▄▃▁▁█▇▆▆▅▃███▇▆▂▁▁▁▁█▇▇▅▄▂▂▁▁▁
wandb:  test_acc_task_0 █▁▄▃▁▃
wandb:  test_acc_task_1 █▂▄▄▁
wandb:  test_acc_task_2 █▆▁▄
wandb:  test_acc_task_3 █▁▂
wandb:  test_acc_task_4 █▁
wandb:  test_acc_task_5 ▁
wandb: test_loss_task_0 ▁▁▁▁▁▁
wandb: test_loss_task_1 ▁▁▁▁▁
wandb: test_loss_task_2 ▁▁▁▁
wandb: test_loss_task_3 ▁▁▁
wandb: test_loss_task_4 ▁▁
wandb: test_loss_task_5 ▁
wandb:       total_loss ██▇▆▅▅▄▄▄▃▃▃▅▅▄▃▃▃▃▃▃▆▆▄▃▂▂▆▅▂▂▂▂▂▂▂▁▁▁▁
wandb:        train_acc ▆▂▃▄▄▅▅▅▅▅▆▂▃▃▃▄▄▄▅▅▅▅▄▆▇███▁▂▂▃▄▅▅▆▆▇▆█
wandb: 
wandb: Run summary:
wandb:     avg_accuracy 0.71847
wandb:       class_loss 0.0112
wandb:            epoch 1020
wa

| Epoch 192, time= 52.4ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 82.1% |
| Epoch 193, time= 52.5ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 81.5% |
| Epoch 194, time= 52.5ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 81.9% |
| Epoch 195, time= 52.5ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 81.3% |
| Epoch 196, time= 52.5ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 81.5% |
| Epoch 197, time= 52.5ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 82.0% |
| Epoch 198, time= 52.5ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 81.4% |
| Epoch 199, time= 52.5ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 81.6% |
| Epoch 200, time= 52.4ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 81.5% |
----------------------------------------------------------------------------------------------------
>>> Test on task  0 - cifa

/home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/src/dataloaders/cifar.py:74: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data[i][s]['x']=torch.load(os.path.join(os.path.ex

Arguments =
	sweep_name: None
	seed: 98
	experiment: cifar
	approach: gvcl
	reg_type: re_g
	q: 1.01
	v: 1
	output: ./res/cifar_gvcl_re_g_98.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
	optimizer: sgd
approach VCL True
Load data...
Task order = [0, 1, 2, 3, 4, 5]
Input size = [3, 32, 32] 
Task info = [(0, 10), (1, 10), (2, 10), (3, 10), (4, 10), (5, 10)]
Inits...
----------------------------------------------------------------------------------------------------
Net(
  (conv_layers): ModuleList(
    (0): MFConvLayer(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): MFConvLayer(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (2): MFConvLayer(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): MFConvLayer(64, 64, kernel_size=(3, 3), stride=(

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:     avg_accuracy ▁▂▄▅▇█
wandb:       class_loss █▆▂▁▇▆▆▆▆▆▅▆▆▆▆▆▅▅▅▅▅▅▅▅▅▄▄▄▄▇▆▆▆▆▆▆▄▄▄▃
wandb:            epoch ▁▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▃▃▃▃▃▄▄▄▄▄▄▆▆▆▆▆▆▇▇▇▇███
wandb:          kl_loss ██▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▃▂▂▂▁▁▁▁▂▁▁▁▁▁▁
wandb:               lr ▅█▇▇▄▃▃▂▂▁▁█▇▆▆▂▂▁▁▁▇▆▃▁▁█▆▅▅▄▂▁▇▅▅▂▁▁▁▁
wandb:  test_acc_task_0 █▄▅▃▃▁
wandb:  test_acc_task_1 █▃▄▁▂
wandb:  test_acc_task_2 █▁▅▄
wandb:  test_acc_task_3 █▃▁
wandb:  test_acc_task_4 █▁
wandb:  test_acc_task_5 ▁
wandb: test_loss_task_0 ▁▁▁▁▁▁
wandb: test_loss_task_1 ▁▁▁▁▁
wandb: test_loss_task_2 ▁▁▁▁
wandb: test_loss_task_3 ▁▁▁
wandb: test_loss_task_4 ▁▁
wandb: test_loss_task_5 ▁
wandb:       total_loss ▄▄▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁█▁▁▁▁▂▂▁▁▁▁▁▁▁
wandb:        train_acc ▁▆▆▆▇▇▇▇▆▆▆▆▇▆▇▇▇▇▇█▅▅▆▆▆▆▆▆▆▆▇▇▆▇▇█████
wandb: 
wandb: Run summary:
wandb:     avg_accuracy 0.71137
wandb:       class_loss 0.01107
wandb:            epoch 1020
w

| Epoch 192, time= 52.6ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 82.4% |
| Epoch 193, time= 52.6ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.031, acc= 82.8% |
| Epoch 194, time= 52.6ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 82.4% |
| Epoch 195, time= 52.6ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.031, acc= 81.9% |
| Epoch 196, time= 52.6ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 82.6% |
| Epoch 197, time= 52.6ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 83.0% |
| Epoch 198, time= 52.6ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 82.5% |
| Epoch 199, time= 52.6ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 82.1% |
| Epoch 200, time= 52.6ms| Train: class_loss=0.011  kl_loss=0.021 total_loss=0.032, acc= 82.3% |
----------------------------------------------------------------------------------------------------
>>> Test on task  0 - cifa

/home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/src/dataloaders/cifar.py:74: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data[i][s]['x']=torch.load(os.path.join(os.path.ex

Arguments =
	sweep_name: None
	seed: 93
	experiment: cifar
	approach: gvcl
	reg_type: re_g
	q: 1.01
	v: 1
	output: ./res/cifar_gvcl_re_g_93.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
	optimizer: sgd
approach VCL True
Load data...
Task order = [0, 1, 2, 3, 4, 5]
Input size = [3, 32, 32] 
Task info = [(0, 10), (1, 10), (2, 10), (3, 10), (4, 10), (5, 10)]
Inits...
----------------------------------------------------------------------------------------------------
Net(
  (conv_layers): ModuleList(
    (0): MFConvLayer(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): MFConvLayer(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (2): MFConvLayer(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): MFConvLayer(64, 64, kernel_size=(3, 3), stride=(

: 

Note that currently gvcl is actually implementing renyi regularization

In [ ]:
import subprocess

# Define the parameters
experiment = "smnist"
approach = "gvcl"
reg_type = "kl_g"
seeds = [1, 23, 47, 61, 93]

# Loop over the seeds and run the experiment
for sd in seeds:
    print(f"Running experiment with seed {sd}")
    subprocess.run([
        "python", "./src/run.py",
        "--use-sweep", "True",
        "--experiment", experiment,
        "--approach", approach,
        "--seed", str(sd),
        "--regularizer", reg_type
    ])

In [ ]:
# Define the parameters
experiment = "cifar"
approach = "gvcl"
reg_type = "kl_g"
seeds = [0, 23, 89, 12]

# Loop over the seeds and run the experiment
for seed in seeds:
    print(f"Running experiment with seed {seed}")
    %run ./src/run.py --experiment $experiment --approach $approach --regularizer $reg_type --seed $seed --train_samples 1

In [ ]:
# Define the parameters
experiment = "cifar"
approach = "gvcl"
reg_type = "kl_g"
seeds = [0, 1, 2, 3]

# Loop over the seeds and run the experiment
for seed in seeds:
    print(f"Running experiment with seed {seed}")
    %run ./src/run.py --experiment $experiment --approach $approach --regularizer $reg_type --seed $seed

In [ ]:
%run ../src/run.py --experiment smnist --approach gvclf --seed 3

In [ ]:
import math

def compute_renyi(alpha, mu0, sigma0, mu1, sigma1):
    """
    Compute the Rényi divergence D_alpha between two normal distributions:
    N(mu0, sigma0^2) and N(mu1, sigma1^2).
    
    Parameters:
    - alpha: The Rényi divergence parameter (alpha > 0, alpha != 1).
    - mu0: Mean of the first distribution.
    - sigma0: Standard deviation of the first distribution.
    - mu1: Mean of the second distribution.
    - sigma1: Standard deviation of the second distribution.
    
    Returns:
    - D_alpha: The Rényi divergence value.
    """
    # Compute sigma^2_alpha
    sigma_alpha_squared = (1 - alpha) * sigma0**2 + alpha * sigma1**2
    if sigma_alpha_squared <= 0:
        raise ValueError("sigma_alpha_squared must be greater than 0.")
    
    # Compute terms of the Rényi divergence
    mean_term = alpha * (mu1 - mu0)**2 / (2 * sigma_alpha_squared)
    log_term = (1 / (1 - alpha)) * math.log(
        (sigma_alpha_squared ** 0.5) / (sigma0 ** (1 - alpha) * sigma1 ** alpha)
    )
    
    # Calculate the Rényi divergence
    D_alpha = mean_term + log_term
    return D_alpha

# Example usage:
alpha = 2.0
mu0 = 0.0
sigma0 = 1.0
mu1 = 1.0
sigma1 = 2.0

result = compute_renyi(alpha, mu0, sigma0, mu1, sigma1)
print(f"Rényi divergence: {result}")


In [ ]:
import torch

def renyi_divergence_univariate_gaussians(mean, log_var, prior_mean, log_prior_var, alpha, sum = True):
    """
    Compute the Rényi divergence between univariate Gaussian posterior and prior distributions.
    
    Args:
        mean (torch.Tensor): Posterior mean (shape: [n]).
        log_var (torch.Tensor): Log-variance of the posterior (shape: [n]).
        prior_mean (torch.Tensor): Prior mean (shape: [n]).
        log_prior_var (torch.Tensor): Log-variance of the prior (shape: [n]).
        alpha (float): Order of the Rényi divergence (alpha > 0, alpha != 1).
    
    Returns:
        torch.Tensor: Rényi divergence for each element in the input tensor (shape: [n]).
    """
    # Compute posterior variance and prior variance from log-variances
    var = torch.exp(log_var)  # Posterior variance
    prior_var = torch.exp(log_prior_var)  # Prior variance

    # Compute the mixed variance (Σ_α)^*
    mixed_var = alpha * prior_var + (1 - alpha) * var

    # Compute the Mahalanobis term: α (μ - μ_prior)^2 / (Σ_α)^*
    mahalanobis_term = alpha * (mean - prior_mean) ** 2 / mixed_var

    # Compute the determinant term: log(|Σ_α^*|) - ((1 - α) log(|Σ|) + α log(|Σ_prior|))
    log_det_term = torch.log(mixed_var) - ((1 - alpha) * log_var + alpha * log_prior_var)

    if sum:
        return 0.5 * torch.sum(mahalanobis_term - 0.5 / (alpha - 1) * log_det_term)
    # Combine terms to compute Rényi divergence
    else:
        return 0.5 * mahalanobis_term - 0.5 / (alpha - 1)

# Example data
mean = torch.tensor([0.5, 0.2, -0.3])
log_var = torch.tensor([-1.0, -0.5, -1.2])
prior_mean = torch.tensor([0.0, 0.0, 0.0])
log_prior_var = torch.tensor([-0.5, -0.5, -0.5])
alpha = 0.5

# Compute Rényi divergence
divergence = renyi_divergence_univariate_gaussians(mean, log_var, prior_mean, log_prior_var, alpha)
print(divergence)



In [ ]:
%run ../src/run.py --experiment easy-chasy --approach hat --seed 0

In [ ]:
%run ../src/run.py --experiment cifar --approach hat

In [ ]:
%run ../src/run.py --experiment cifar --approach gvclf --seed 3

In [ ]:
import torch
print(torch.cuda.is_available())

In [ ]:
%run ../src/run.py --experiment cifar --approach gvclf

In [ ]:
%run ../src/run.py --experiment smnist --approach hat --seed 14

In [ ]:
import matplotlib.pyplot as plt

def calculate_average_accuracy(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
    
    average_accuracies = []
    
    for i, line in enumerate(lines):
        values = list(map(float, line.split()))
        non_zero_values = values[:i+1]
        average_accuracy = sum(non_zero_values) / len(non_zero_values)
        average_accuracies.append(average_accuracy)
        print(f"Row {i+1} average accuracy: {average_accuracy:.4f}")
    
    return average_accuracies

def plot_accuracies(accuracies):
    plt.plot(range(1, len(accuracies) + 1), accuracies, marker='o')
    plt.xlabel('Number of Tasks Learned')
    plt.ylabel('Average Accuracy')
    plt.title('Average Accuracy Across Tasks')
    plt.grid(True)
    plt.show()

# Calculate average accuracies
average_accuracies = calculate_average_accuracy('../res/smnist_gvclf_14.txt')

# Plot the accuracies
plot_accuracies(average_accuracies)

In [ ]:
import matplotlib.pyplot as plt

def calculate_average_accuracy(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
    
    average_accuracies = []
    
    for i, line in enumerate(lines):
        values = list(map(float, line.split()))
        non_zero_values = values[:i+1]
        average_accuracy = sum(non_zero_values) / len(non_zero_values)
        average_accuracies.append(average_accuracy)
        #print(f"Row {i+1} average accuracy: {average_accuracy:.4f}")
    
    return average_accuracies

def plot_accuracies(file_paths):
    for file_path in file_paths:
        accuracies = calculate_average_accuracy(file_path)
        plt.plot(range(1, len(accuracies) + 1), accuracies, marker='o', label=file_path)
    
    plt.xlabel('Number of Tasks Learned')
    plt.ylabel('Average Accuracy')
    plt.title('Average Accuracy Across Tasks')
    plt.legend()
    plt.grid(True)
    plt.show()

# List of result files
result_files = [
    '../res/smnist_gvcl_0.txt',
    '../res/smnist_hat_0.txt',
    '../res/smnist_vcrenyi_3.txt',
]

# Plot the accuracies for each result file
plot_accuracies(result_files)