In [14]:
%load_ext autoreload
%autoreload 2


%run ./src/run.py --help


usage: run.py [-h] [--sweep_name SWEEP_NAME] [--seed SEED] --experiment
              {mnist2,pmnist,cifar,mixture,easy-chasy,hard-chasy,smnist,omniglot}
              --approach
              {random,sgd,sgd-frozen,lwf,lfl,ewc,imm-mean,progressive,pathnet,imm-mode,sgd-restart,ewc2,ewc-film,joint,hat,hat-test,gvcl,vcl,vclf,gvclf}
              [--reg_type {t_st,kl_g,re_g,kl_qg,re_qg}] [--q Q] [--v V]
              [--output OUTPUT] [--nepochs NEPOCHS] [--lr LR]
              [--parameter PARAMETER] [--ntasks NTASKS] [--momentum MOMENTUM]
              [--weight_decay WEIGHT_DECAY] [--beta BETA] [--lamb LAMB]
              [--root_path ROOT_PATH]
              [--use-best-hyperparams USE_BEST_HYPERPARAMS]
              [--use-sweep USE_SWEEP] [--train_samples TRAIN_SAMPLES]
              [--lr_schedule LR_SCHEDULE] [--scheduler_type SCHEDULER_TYPE]
              [--sbatch SBATCH]

xxx

options:
  -h, --help            show this help message and exit
  --sweep_name SWEEP_NAME
           

In [1]:
import torch
print(torch.cuda.is_available())

True


In [16]:
import subprocess

# Define the parameters
experiment = "smnist"
approach = "gvcl"
reg_type = "t_st"
dof = [50]
seed = 187

# Loop over the seeds and run the experiment
for v in dof:
    print(f"Running experiment with dof {v}")
    subprocess.run([
        "python", "./src/run.py",
        "--experiment", experiment,
        "--approach", approach,
        "--v", str(v),
        "--seed", str(seed),
        "--use-sweep", str(True),
        "--reg_type", reg_type
    ])

Running experiment with dof 50


wandb: Currently logged in as: naima-elosegui (nagiu). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.3
wandb: Run data is saved locally in /home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/wandb/run-20250126_021553-qlygnhxj
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run devoted-flower-1494
wandb: ⭐️ View project at https://wandb.ai/nagiu/curvy-cl
wandb: 🚀 View run at https://wandb.ai/nagiu/curvy-cl/runs/qlygnhxj


Arguments =
	sweep_name: None
	seed: 187
	experiment: smnist
	approach: gvcl
	reg_type: t_st
	q: 1.01
	v: 50
	output: ./res/smnist/gvcl/t_st/187.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([1, 1, 1,  ..., 1, 0, 1])
tensor([0, 0, 1,  ..., 0, 0, 1])
tensor([0, 1, 0,  ..., 0, 1, 1])
tensor([1, 1, 1,  ..., 0, 0, 1])
tensor([1, 1, 0,  ..., 0, 1, 1])
tensor([1, 1, 0,  ..., 1, 1, 0])
tensor([1, 1, 1,  ..., 1, 1, 0])
tensor([0, 0, 1,  ..., 0, 0, 0])
tensor([1, 1, 1,  ..., 0, 1, 1])
tensor([1, 1, 0,  ..., 1, 1, 0])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1, 2), (2, 2), (3, 2), (4, 2

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:        avg_accuracy ▁▂▃▃▄▅▆▇██
wandb:          class_loss ▁▁▁▅▃▃▃▃▂▂▂▃▁▁▁▁▁█▄▃▂▂▅▂▂▄▂▃▃▃▃▂▂▂█▂▂▂▂▂
wandb:               epoch ▁▁▁▁▂▂▂▂▂▃▃▃▃▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇▇▇▇▇▇█
wandb:             kl_loss █████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:       kl_term_batch █████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: kl_term_unormalized █████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                  lr █▇▆▅▃▁▃▁█▇▆▄▃▂▂▄▂▁▇▆▆▄▃▁▇▁▇▇▃▁▇▇▆▄▃▁▁█▇▁
wandb:     test_acc_task_0 █▆▆▄▁▄▅▄▄▅
wandb:     test_acc_task_1 █▁▂▂▂▁▂▄▂
wandb:     test_acc_task_2 █▁▁▁▂▂▁▁
wandb:     test_acc_task_3 █▂▁▂▂▁▂
wandb:     test_acc_task_4 █▁▂▂▁▂
wandb:     test_acc_task_5 █▅▁▂▂
wandb:     test_acc_task_6 █▃▂▁
wandb:     test_acc_task_7 █▂▁
wandb:     test_acc_task_8 █▁
wandb:     test_acc_task_9 ▁
wandb:    test_loss_task_0 ▁▁▁▁▁▁▁▁▁▁
wandb:    test_loss_task_1 ▁▁▁▁▁▁▁▁▁
wandb:    test_loss_task_2 ▁▁

>>> Test on task  4 - mnist-8-9      : loss=-1.000, acc= 50.9% <<<
>>> Test on task  5 - kmnist-0-1     : loss=-1.000, acc= 72.7% <<<
>>> Test on task  6 - kmnist-2-3     : loss=-1.000, acc= 94.5% <<<
Average accuracy: 43.2%
Save at ./res/smnist/gvcl/t_st/187.txt
****************************************************************************************************
Task  7 (kmnist-4-5)
****************************************************************************************************
training for 11 epochs
Total number of steps per task 7: 1856
Scheduling on.
| Epoch   1, time= 56.7ms| Train: class_loss=0.002  kl_loss=0.327 total_loss=0.330, acc= 94.5% |
| Epoch   2, time= 57.2ms| Train: class_loss=0.001  kl_loss=0.255 total_loss=0.256, acc= 97.8% |
| Epoch   3, time= 57.1ms| Train: class_loss=0.001  kl_loss=0.189 total_loss=0.190, acc= 98.4% |
| Epoch   4, time= 57.0ms| Train: class_loss=0.001  kl_loss=0.132 total_loss=0.133, acc= 98.6% |
| Epoch   5, time= 57.2ms| Train: class_loss=0.0

## Run experiments

In [2]:
import subprocess

# Define the parameters
experiment = "cifar"
approach = "gvcl"
reg_type = "kl_g"
seed = [32,54,76,98,93] #missing 98 and 93

# Loop over the seeds and run the experiment
for sd in seed:
    print(f"Running experiment with seed {sd}")
    subprocess.run([
        "python", "./src/run.py",
        "--experiment", experiment,
        "--approach", approach,
        "--seed", str(sd),
        "--use-sweep", str(True),
        "--reg_type", reg_type
    ])

Running experiment with seed 32


/home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/src/dataloaders/cifar.py:74: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data[i][s]['x']=torch.load(os.path.join(os.path.ex

Arguments =
	sweep_name: None
	seed: 32
	experiment: cifar
	approach: gvcl
	reg_type: kl_g
	q: 1.01
	v: 1
	output: ./res/cifar/gvcl/kl_g/32.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
approach VCL True
Load data...
Task order = [0, 1, 2, 3, 4, 5]
Input size = [3, 32, 32] 
Task info = [(0, 10), (1, 10), (2, 10), (3, 10), (4, 10), (5, 10)]
Inits...
Film type none
----------------------------------------------------------------------------------------------------
Net(
  (conv_layers): ModuleList(
    (0): MFConvLayer(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): MFConvLayer(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (2): MFConvLayer(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): MFConvLayer(64, 64, kernel_size=(3, 3), stride=(1

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:        avg_accuracy ▁▂▄▅▇█
wandb:          class_loss ▂▂▂▁▁▁▁▁▂▂▂▂▂▂▁▁█▂▁▁▁▁▁▁▁▂▂▂▂▂▁▁▁▁▂▁▁▁▁▁
wandb:               epoch ▁▁▁▁▁▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▆▇▇▇▇█
wandb:             kl_loss ▃▃▃▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂█▂▁▁▁▂▂▁▁▁▁▁▁▁▁▁▁
wandb:       kl_term_batch ███████▅▄▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: kl_term_unormalized █████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                  lr ▆▁▇▇▆▅▄▂▁▁▁▁█▁▁██▇▇▆▆▅▄▄▄█████▆▂▁▁▇▅▂▂▁▁
wandb:     test_acc_task_0 █▃▄��▁▁
wandb:     test_acc_task_1 █▄▃▂▁
wandb:     test_acc_task_2 █▄▁▂
wandb:     test_acc_task_3 █▁▁
wandb:     test_acc_task_4 █▁
wandb:     test_acc_task_5 ▁
wandb:    test_loss_task_0 ▁▁▁▁▁▁
wandb:    test_loss_task_1 ▁▁▁▁▁
wandb:    test_loss_task_2 ▁▁▁▁
wandb:    test_loss_task_3 ▁▁▁
wandb:    test_loss_task_4 ▁▁
wandb:    test_loss_task_5 ▁
wandb:          total_loss █▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▆▁▁▁▁▁▁▁▁▁▁▁▁▁

| Epoch 192, time= 54.2ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 96.1% |
| Epoch 193, time= 54.2ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 96.2% |
| Epoch 194, time= 54.2ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 96.2% |
| Epoch 195, time= 54.2ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.4% |
| Epoch 196, time= 54.2ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.5% |
| Epoch 197, time= 54.2ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 95.9% |
| Epoch 198, time= 54.2ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 96.5% |
| Epoch 199, time= 54.2ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.020, acc= 96.4% |
| Epoch 200, time= 54.2ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.3% |
----------------------------------------------------------------------------------------------------
>>> Test on task  0 - cifa

/home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/src/dataloaders/cifar.py:74: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data[i][s]['x']=torch.load(os.path.join(os.path.ex

Arguments =
	sweep_name: None
	seed: 54
	experiment: cifar
	approach: gvcl
	reg_type: kl_g
	q: 1.01
	v: 1
	output: ./res/cifar/gvcl/kl_g/54.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
approach VCL True
Load data...
Task order = [0, 1, 2, 3, 4, 5]
Input size = [3, 32, 32] 
Task info = [(0, 10), (1, 10), (2, 10), (3, 10), (4, 10), (5, 10)]
Inits...
Film type none
----------------------------------------------------------------------------------------------------
Net(
  (conv_layers): ModuleList(
    (0): MFConvLayer(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): MFConvLayer(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (2): MFConvLayer(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): MFConvLayer(64, 64, kernel_size=(3, 3), stride=(1

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:        avg_accuracy ▁▂▄▅▇█
wandb:          class_loss █▂▂▂▂▁▁▁▁▁▂▂▂▂▂▁▁▁▂▂▁▁▁▁▁▂▂▂▂▂▁█▁▁▁▁▁▁▁▁
wandb:               epoch ▁▁▂▂▂▂▃▃▃▃▄▄▄▄▄▄▄▄▅▅▅▅▅▅▅▅▅▆▆▆▆▆▇▇▇█████
wandb:             kl_loss █▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:       kl_term_batch █████▂▂▂▂▂▅▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: kl_term_unormalized █████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                  lr █▆▄▃▂▂▂▁▆▅▄▁▁▁▁▆▂▂▁▁██▅▅▁▁▁▁▁█▆▆▅▅▅▄▃▃▁▁
wandb:     test_acc_task_0 █▃▅��▁▁
wandb:     test_acc_task_1 █▁▁▁▁
wandb:     test_acc_task_2 █▅▁▃
wandb:     test_acc_task_3 █▂▁
wandb:     test_acc_task_4 █▁
wandb:     test_acc_task_5 ▁
wandb:    test_loss_task_0 ▁▁▁▁▁▁
wandb:    test_loss_task_1 ▁▁▁▁▁
wandb:    test_loss_task_2 ▁▁▁▁
wandb:    test_loss_task_3 ▁▁▁
wandb:    test_loss_task_4 ▁▁
wandb:    test_loss_task_5 ▁
wandb:          total_loss ██▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▂▁▁▁▁▁▆▂▁▁▁▁▁▁▁

| Epoch 192, time= 54.1ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.4% |
| Epoch 193, time= 54.3ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.3% |
| Epoch 194, time= 54.3ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.2% |
| Epoch 195, time= 54.3ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.4% |
| Epoch 196, time= 54.2ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.4% |
| Epoch 197, time= 54.2ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.1% |
| Epoch 198, time= 54.2ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.4% |
| Epoch 199, time= 54.2ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.2% |
| Epoch 200, time= 54.2ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.2% |
----------------------------------------------------------------------------------------------------
>>> Test on task  0 - cifa

/home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/src/dataloaders/cifar.py:74: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data[i][s]['x']=torch.load(os.path.join(os.path.ex

Arguments =
	sweep_name: None
	seed: 76
	experiment: cifar
	approach: gvcl
	reg_type: kl_g
	q: 1.01
	v: 1
	output: ./res/cifar/gvcl/kl_g/76.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
approach VCL True
Load data...
Task order = [0, 1, 2, 3, 4, 5]
Input size = [3, 32, 32] 
Task info = [(0, 10), (1, 10), (2, 10), (3, 10), (4, 10), (5, 10)]
Inits...
Film type none
----------------------------------------------------------------------------------------------------
Net(
  (conv_layers): ModuleList(
    (0): MFConvLayer(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): MFConvLayer(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (2): MFConvLayer(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): MFConvLayer(64, 64, kernel_size=(3, 3), stride=(1

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:        avg_accuracy ▁▂▄▅▇█
wandb:          class_loss █▄▂▂▃▂▂▁▁▁▁▁▁▁▂▂▂▂▂▁▁▁▅▂▂▁▁▁▁▁▂▂▂▂▁▁▁▁▁▁
wandb:               epoch ▁▁▁▁▁▂▂▃▃▃▄▄▄▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇▇█████
wandb:             kl_loss ██▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁
wandb:       kl_term_batch █████▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: kl_term_unormalized ██████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                  lr █▇▇▇▅▄▄▄▂▂▁▁▁▁█▄▂▁▁▁▇▆▆▄▃▃▁██▇▂▁▁▁█▇▆▃▁▁
wandb:     test_acc_task_0 █▁▄��▁▂
wandb:     test_acc_task_1 █▄▄▁▃
wandb:     test_acc_task_2 █▂▁▃
wandb:     test_acc_task_3 █▄▁
wandb:     test_acc_task_4 █▁
wandb:     test_acc_task_5 ▁
wandb:    test_loss_task_0 ▁▁▁▁▁▁
wandb:    test_loss_task_1 ▁▁▁▁▁
wandb:    test_loss_task_2 ▁▁▁▁
wandb:    test_loss_task_3 ▁▁▁
wandb:    test_loss_task_4 ▁▁
wandb:    test_loss_task_5 ▁
wandb:          total_loss ██▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▆▂▂▁▁▁▁▁▄▂▁▁▁▁

| Epoch 192, time= 54.5ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.3% |
| Epoch 193, time= 54.6ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.2% |
| Epoch 194, time= 54.5ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.2% |
| Epoch 195, time= 54.6ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.1% |
| Epoch 196, time= 54.5ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.2% |
| Epoch 197, time= 54.6ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.0% |
| Epoch 198, time= 54.6ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.2% |
| Epoch 199, time= 54.5ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 96.2% |
| Epoch 200, time= 54.6ms| Train: class_loss=0.005  kl_loss=0.015 total_loss=0.019, acc= 95.9% |
----------------------------------------------------------------------------------------------------
>>> Test on task  0 - cifa

/home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/src/dataloaders/cifar.py:74: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data[i][s]['x']=torch.load(os.path.join(os.path.ex

Arguments =
	sweep_name: None
	seed: 98
	experiment: cifar
	approach: gvcl
	reg_type: kl_g
	q: 1.01
	v: 1
	output: ./res/cifar/gvcl/kl_g/98.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
approach VCL True
Load data...
Task order = [0, 1, 2, 3, 4, 5]
Input size = [3, 32, 32] 
Task info = [(0, 10), (1, 10), (2, 10), (3, 10), (4, 10), (5, 10)]
Inits...
Film type none
----------------------------------------------------------------------------------------------------
Net(
  (conv_layers): ModuleList(
    (0): MFConvLayer(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): MFConvLayer(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (2): MFConvLayer(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): MFConvLayer(64, 64, kernel_size=(3, 3), stride=(1

: 

In [11]:
import subprocess

# Define the parameters
experiment = "smnist"
approach = "vcl"
reg_type = "re_g"
seed = [32,54,76,98,93]

# Loop over the seeds and run the experiment
for sd in seed:
    print(f"Running experiment with seed {sd}")
    subprocess.run([
        "python", "./src/run.py",
        "--experiment", experiment,
        "--approach", approach,
        "--seed", str(sd),
        "--use-sweep", str(True),
        "--reg_type", reg_type
    ])

Running experiment with seed 32


wandb: Currently logged in as: naima-elosegui (nagiu). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.3
wandb: Run data is saved locally in /home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/wandb/run-20250125_153308-pv7uhosq
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run skilled-star-1383
wandb: ⭐️ View project at https://wandb.ai/nagiu/curvy-cl
wandb: 🚀 View run at https://wandb.ai/nagiu/curvy-cl/runs/pv7uhosq


Arguments =
	sweep_name: None
	seed: 32
	experiment: smnist
	approach: vcl
	reg_type: re_g
	q: 1.01
	v: 1
	output: ./res/smnist/vcl/re_g/32.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([1, 0, 1,  ..., 1, 1, 1])
tensor([1, 1, 1,  ..., 0, 0, 1])
tensor([1, 1, 0,  ..., 1, 0, 1])
tensor([0, 1, 1,  ..., 1, 1, 0])
tensor([0, 0, 1,  ..., 0, 1, 0])
tensor([0, 0, 0,  ..., 0, 1, 0])
tensor([0, 0, 0,  ..., 0, 0, 1])
tensor([0, 1, 1,  ..., 0, 0, 0])
tensor([1, 0, 1,  ..., 0, 1, 0])
tensor([0, 1, 0,  ..., 0, 0, 1])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1, 2), (2, 2), (3, 2), (4, 2), (5

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:        avg_accuracy ▁▂▃▃▄▅▆▆▇█
wandb:          class_loss ▁▁▁▁▁▃▃▆▂▂▂▁▁▁▁▃▃▂▂▂▂▂▂▂▃▃▃▇▃▃▃▃▃▃▂█▂▂▂▂
wandb:               epoch ▁▁▁▁▁▂▂▂▃▃▃▃▄▄▄▅▅▅▆▆▆▆▇▇▇▇▇▇▇▇▇▇▇███████
wandb:             kl_loss ████▃▁▁▁▁▁▁▁▁▁▁▁▃▁▁▁▁▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▃▁
wandb:       kl_term_batch █████▁▁▁▁▁▂▁▁▁▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: kl_term_unormalized ███████▁▁▁▁▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▁▁▁▁▁▁▁▁▁
wandb:                  lr ▆▅▂▁▁▇▇▆▂▁▅▄▃▁▁▇▇▆▁█▆▁▇▆▅▂▂▁█▇▁█▇▃▁▇▇▅▃▁
wandb:     test_acc_task_0 ▁▁▁█▁▁▁▁▁▁
wandb:     test_acc_task_1 █▃▃▁▄▇▅▅▆
wandb:     test_acc_task_2 ██▂▁▂▁▃▃
wandb:     test_acc_task_3 █▂▄▂▃▁▂
wandb:     test_acc_task_4 █▆▆▁▃▅
wandb:     test_acc_task_5 █▆█▁▁
wandb:     test_acc_task_6 █▆▂▁
wandb:     test_acc_task_7 █▆▁
wandb:     test_acc_task_8 █▁
wandb:     test_acc_task_9 ▁
wandb:    test_loss_task_0 ▁▁▁▁▁▁▁▁▁▁
wandb:    test_loss_task_1 ▁▁▁▁▁▁▁▁▁
wandb:    test_loss_task_2 ▁▁

>>> Test on task  5 - kmnist-0-1     : loss=-1.000, acc= 97.8% <<<
>>> Test on task  6 - kmnist-2-3     : loss=-1.000, acc= 92.8% <<<
Average accuracy: 68.5%
Save at ./res/smnist/vcl/re_g/32.txt
****************************************************************************************************
Task  7 (kmnist-4-5)
****************************************************************************************************
training for 11 epochs
Total number of steps per task 7: 1856
Scheduling on.
| Epoch   1, time= 16.8ms| Train: class_loss=0.004  kl_loss=0.130 total_loss=0.135, acc= 87.2% |
| Epoch   2, time= 16.9ms| Train: class_loss=0.002  kl_loss=0.009 total_loss=0.011, acc= 96.9% |
| Epoch   3, time= 16.9ms| Train: class_loss=0.001  kl_loss=0.007 total_loss=0.009, acc= 97.7% |
| Epoch   4, time= 16.9ms| Train: class_loss=0.001  kl_loss=0.004 total_loss=0.006, acc= 97.8% |
| Epoch   5, time= 16.9ms| Train: class_loss=0.001  kl_loss=0.004 total_loss=0.005, acc= 97.9% |
| Epoch   6, time= 1

wandb: Currently logged in as: naima-elosegui (nagiu). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.3
wandb: Run data is saved locally in /home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/wandb/run-20250125_153921-0u2g4q6i
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run fiery-spaceship-1384
wandb: ⭐️ View project at https://wandb.ai/nagiu/curvy-cl
wandb: 🚀 View run at https://wandb.ai/nagiu/curvy-cl/runs/0u2g4q6i


Arguments =
	sweep_name: None
	seed: 54
	experiment: smnist
	approach: vcl
	reg_type: re_g
	q: 1.01
	v: 1
	output: ./res/smnist/vcl/re_g/54.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([1, 1, 1,  ..., 0, 1, 0])
tensor([0, 1, 0,  ..., 1, 1, 1])
tensor([1, 0, 0,  ..., 1, 1, 0])
tensor([0, 1, 1,  ..., 0, 1, 1])
tensor([1, 0, 1,  ..., 0, 0, 1])
tensor([1, 1, 1,  ..., 0, 0, 1])
tensor([0, 0, 0,  ..., 1, 0, 0])
tensor([1, 1, 1,  ..., 1, 0, 0])
tensor([1, 1, 1,  ..., 1, 0, 0])
tensor([0, 1, 0,  ..., 1, 1, 1])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1, 2), (2, 2), (3, 2), (4, 2), (5

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:        avg_accuracy ▁▂▃▃▄▅▆▆▇█
wandb:          class_loss ▁▁▁▁▁▃▃▃▃▇▂▂▂▁▁▇▃▃▂▂▂▂▂▂▇▃▃▃▃▃▃▇▃▃▂█▃▂▂▂
wandb:               epoch ▁▁▁▂▂▂▂▃▃▃▄▄▄▄▄▄▄▅▅▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇▇▇▇█
wandb:             kl_loss ███████▁▁▁▁▁▁▁▁▁▁▁▃▁▁▁▁▁▁▁▃▁▁▃▁▁▁▃▁▁▁▁▁▁
wandb:       kl_term_batch ██▄▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: kl_term_unormalized ████▃▁▁▁▁▁▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                  lr █▃▁▁█▆▁▁▇▆▂▁▁▆▂█▇▃▂▇▁█▃▂▁▆▅▂▁█▅▃▂▂█▃▂▂▁▁
wandb:     test_acc_task_0 █████▅▁▅██
wandb:     test_acc_task_1 ███▁▅▄▅▇▇
wandb:     test_acc_task_2 █▇▃▄▄▃▁▃
wandb:     test_acc_task_3 █▂▅▁▂▂▄
wandb:     test_acc_task_4 ███▇▁▁
wandb:     test_acc_task_5 █▆█▄▁
wandb:     test_acc_task_6 █▆▃▁
wandb:     test_acc_task_7 █▁▂
wandb:     test_acc_task_8 █▁
wandb:     test_acc_task_9 ▁
wandb:    test_loss_task_0 ▁▁▁▁▁▁▁▁▁▁
wandb:    test_loss_task_1 ▁▁▁▁▁▁▁▁▁
wandb:    test_loss_task_2 ▁▁

>>> Test on task  5 - kmnist-0-1     : loss=-1.000, acc= 97.8% <<<
>>> Test on task  6 - kmnist-2-3     : loss=-1.000, acc= 93.5% <<<
Average accuracy: 68.4%
Save at ./res/smnist/vcl/re_g/54.txt
****************************************************************************************************
Task  7 (kmnist-4-5)
****************************************************************************************************
training for 11 epochs
Total number of steps per task 7: 1856
Scheduling on.
| Epoch   1, time= 17.1ms| Train: class_loss=0.004  kl_loss=0.131 total_loss=0.135, acc= 88.3% |
| Epoch   2, time= 17.1ms| Train: class_loss=0.002  kl_loss=0.009 total_loss=0.011, acc= 96.8% |
| Epoch   3, time= 17.1ms| Train: class_loss=0.002  kl_loss=0.007 total_loss=0.009, acc= 97.4% |
| Epoch   4, time= 17.1ms| Train: class_loss=0.001  kl_loss=0.004 total_loss=0.006, acc= 98.0% |
| Epoch   5, time= 17.1ms| Train: class_loss=0.001  kl_loss=0.004 total_loss=0.005, acc= 97.9% |
| Epoch   6, time= 1

wandb: Currently logged in as: naima-elosegui (nagiu). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.3
wandb: Run data is saved locally in /home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/wandb/run-20250125_154538-ntssrfz7
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run solar-morning-1386
wandb: ⭐️ View project at https://wandb.ai/nagiu/curvy-cl
wandb: 🚀 View run at https://wandb.ai/nagiu/curvy-cl/runs/ntssrfz7


Arguments =
	sweep_name: None
	seed: 76
	experiment: smnist
	approach: vcl
	reg_type: re_g
	q: 1.01
	v: 1
	output: ./res/smnist/vcl/re_g/76.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([0, 1, 1,  ..., 1, 0, 0])
tensor([0, 1, 0,  ..., 0, 0, 0])
tensor([1, 0, 0,  ..., 0, 0, 0])
tensor([1, 0, 0,  ..., 1, 1, 1])
tensor([1, 0, 0,  ..., 0, 0, 0])
tensor([1, 0, 0,  ..., 1, 1, 0])
tensor([1, 1, 1,  ..., 1, 1, 1])
tensor([0, 1, 0,  ..., 0, 0, 0])
tensor([1, 0, 1,  ..., 1, 0, 0])
tensor([0, 1, 0,  ..., 1, 0, 1])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1, 2), (2, 2), (3, 2), (4, 2), (5

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:        avg_accuracy ▁▂▃▃▄▅▆▆▇█
wandb:          class_loss ▅▁▁▄▄▃█▂▂▂▅▂▁▁▁▁▃▃▃▃▂▂▂▃▃▃▃▄▄▃▄▃▃▃▃▃▃▃▃▃
wandb:               epoch ▁▁▁▁▁▂▂▃▃▃▃▃▄▄▄▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▇▇▇▇▇▇███
wandb:             kl_loss ████▃▁▁▁▁▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▃▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:       kl_term_batch ██████▂▁▁▂▁▁▁▁▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: kl_term_unormalized █▁▁▁▁▁▁▁▁▁▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▁▁
wandb:                  lr ▆▅▁▁█▅▃▂▁▆▂▁▁█▆▄▂▁█▇▇▇▃▁█▅▃▂▇▇▂▁▁▇▅▂▁▁▆▂
wandb:     test_acc_task_0 █▆▆▆▆▆▆▁▆▆
wandb:     test_acc_task_1 █▆▆▁▅▅▅▆▇
wandb:     test_acc_task_2 ██▄▂▂▃▁▁
wandb:     test_acc_task_3 █▃▂▁▄▃▄
wandb:     test_acc_task_4 ▆█▆▆▄▁
wandb:     test_acc_task_5 █▃▅▄▁
wandb:     test_acc_task_6 █▅▂▁
wandb:     test_acc_task_7 █▁▁
wandb:     test_acc_task_8 █▁
wandb:     test_acc_task_9 ▁
wandb:    test_loss_task_0 ▁▁▁▁▁▁▁▁▁▁
wandb:    test_loss_task_1 ▁▁▁▁▁▁▁▁▁
wandb:    test_loss_task_2 ▁▁

>>> Test on task  5 - kmnist-0-1     : loss=-1.000, acc= 97.9% <<<
>>> Test on task  6 - kmnist-2-3     : loss=-1.000, acc= 93.0% <<<
Average accuracy: 68.4%
Save at ./res/smnist/vcl/re_g/76.txt
****************************************************************************************************
Task  7 (kmnist-4-5)
****************************************************************************************************
training for 11 epochs
Total number of steps per task 7: 1856
Scheduling on.
| Epoch   1, time= 17.1ms| Train: class_loss=0.005  kl_loss=0.131 total_loss=0.136, acc= 88.7% |
| Epoch   2, time= 16.8ms| Train: class_loss=0.002  kl_loss=0.009 total_loss=0.011, acc= 96.6% |
| Epoch   3, time= 16.9ms| Train: class_loss=0.002  kl_loss=0.007 total_loss=0.009, acc= 97.5% |
| Epoch   4, time= 17.0ms| Train: class_loss=0.001  kl_loss=0.004 total_loss=0.006, acc= 97.7% |
| Epoch   5, time= 16.8ms| Train: class_loss=0.001  kl_loss=0.004 total_loss=0.005, acc= 98.0% |
| Epoch   6, time= 1

wandb: Currently logged in as: naima-elosegui (nagiu). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.3
wandb: Run data is saved locally in /home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/wandb/run-20250125_155155-ztbputz7
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run still-lion-1387
wandb: ⭐️ View project at https://wandb.ai/nagiu/curvy-cl
wandb: 🚀 View run at https://wandb.ai/nagiu/curvy-cl/runs/ztbputz7


Arguments =
	sweep_name: None
	seed: 98
	experiment: smnist
	approach: vcl
	reg_type: re_g
	q: 1.01
	v: 1
	output: ./res/smnist/vcl/re_g/98.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([0, 1, 0,  ..., 1, 1, 1])
tensor([0, 1, 0,  ..., 0, 0, 0])
tensor([0, 1, 0,  ..., 1, 0, 0])
tensor([0, 0, 1,  ..., 0, 1, 1])
tensor([1, 1, 0,  ..., 1, 1, 0])
tensor([1, 0, 0,  ..., 0, 0, 0])
tensor([0, 0, 0,  ..., 1, 0, 0])
tensor([1, 0, 1,  ..., 0, 1, 1])
tensor([1, 0, 0,  ..., 1, 0, 1])
tensor([0, 1, 0,  ..., 1, 0, 1])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1, 2), (2, 2), (3, 2), (4, 2), (5

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:        avg_accuracy ▁▂▃▃▄▅▆▇▇█
wandb:          class_loss ▁▁▁▁▁▄▃▃▂▂▂▂▂▂▅▁█▃▂▆▂▂▇▄▃▃█▄▃▃▃▃▃▃▃▃▃▃▂▂
wandb:               epoch ▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇▇▇█████
wandb:             kl_loss ████▃▁▁▁▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▃▁▁▁▁▁▁▁▁
wandb:       kl_term_batch █████▁▁▁▁▁▂▁▃▁▁▁▁▁▁▁▁▁▃▁▁▁▁▁▁▁▁▁▁▁▁▁▂▁▁▁
wandb: kl_term_unormalized ████▂▁▁▁▁▁▁▁▁▁▁▁▁▁▄▂▁▁▁▁▃▁▁▁▁▁▁▂▁▁▁▁▁▁▁▁
wandb:                  lr ▆▄▁▁▁▆▅▁▇▅▂▁█▇▄▁▁█▇▆▂▂▁▁▆▂█▇▇▆▁▇▅▂▇▅▃▂▁▁
wandb:     test_acc_task_0 ███████▁█▁
wandb:     test_acc_task_1 █▇▇▁▄▁▃▂▂
wandb:     test_acc_task_2 ▇█▄▄▃▃▁▄
wandb:     test_acc_task_3 █▁▂▄▇▆█
wandb:     test_acc_task_4 █▇█▄▁▄
wandb:     test_acc_task_5 ▄▆█▃▁
wandb:     test_acc_task_6 ██▇▁
wandb:     test_acc_task_7 █▅▁
wandb:     test_acc_task_8 █▁
wandb:     test_acc_task_9 ▁
wandb:    test_loss_task_0 ▁▁▁▁▁▁▁▁▁▁
wandb:    test_loss_task_1 ▁▁▁▁▁▁▁▁▁
wandb:    test_loss_task_2 ▁▁

>>> Test on task  5 - kmnist-0-1     : loss=-1.000, acc= 98.0% <<<
>>> Test on task  6 - kmnist-2-3     : loss=-1.000, acc= 93.5% <<<
Average accuracy: 68.3%
Save at ./res/smnist/vcl/re_g/98.txt
****************************************************************************************************
Task  7 (kmnist-4-5)
****************************************************************************************************
training for 11 epochs
Total number of steps per task 7: 1856
Scheduling on.
| Epoch   1, time= 17.3ms| Train: class_loss=0.005  kl_loss=0.131 total_loss=0.136, acc= 86.3% |
| Epoch   2, time= 17.3ms| Train: class_loss=0.002  kl_loss=0.009 total_loss=0.011, acc= 96.9% |
| Epoch   3, time= 17.3ms| Train: class_loss=0.001  kl_loss=0.007 total_loss=0.008, acc= 97.8% |
| Epoch   4, time= 17.3ms| Train: class_loss=0.001  kl_loss=0.004 total_loss=0.006, acc= 97.9% |
| Epoch   5, time= 17.3ms| Train: class_loss=0.001  kl_loss=0.004 total_loss=0.005, acc= 97.8% |
| Epoch   6, time= 1

wandb: Currently logged in as: naima-elosegui (nagiu). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.3
wandb: Run data is saved locally in /home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/wandb/run-20250125_155816-r5x2t7ew
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run northern-oath-1389
wandb: ⭐️ View project at https://wandb.ai/nagiu/curvy-cl
wandb: 🚀 View run at https://wandb.ai/nagiu/curvy-cl/runs/r5x2t7ew


Arguments =
	sweep_name: None
	seed: 93
	experiment: smnist
	approach: vcl
	reg_type: re_g
	q: 1.01
	v: 1
	output: ./res/smnist/vcl/re_g/93.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
	lr_schedule: False
	scheduler_type: cosine_anneal
	sbatch: 64
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([1, 0, 0,  ..., 0, 0, 0])
tensor([0, 0, 0,  ..., 1, 0, 1])
tensor([0, 0, 0,  ..., 1, 1, 1])
tensor([1, 1, 1,  ..., 0, 1, 1])
tensor([0, 0, 0,  ..., 0, 1, 1])
tensor([1, 1, 0,  ..., 0, 0, 0])
tensor([1, 1, 1,  ..., 1, 0, 0])
tensor([0, 0, 0,  ..., 0, 1, 0])
tensor([1, 0, 1,  ..., 0, 0, 0])
tensor([1, 1, 0,  ..., 1, 1, 0])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1, 2), (2, 2), (3, 2), (4, 2), (5

wandb:                                                                                
wandb: 
wandb: Run history:
wandb:        avg_accuracy ▁▂▃▃▄▅▆▇▇█
wandb:          class_loss ▄▁▁▁▁▃▃█▂▂▂▁▁▁▁▃▃▃▂▂▂▂▂█▄▃▃▃▃▄▃▃▃▃▃▃▃▃▃▃
wandb:               epoch ▁▁▁▂▂▃▃▃▄▄▄▄▄▅▅▅▅▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇▇▇▇███
wandb:             kl_loss ████▁▁▁▁▃▁▁▁▁▁▁▃▁▁▁▁▁▁▁▁▁▁▁▁▃▁▁▁▁▁▁▁▁▃▁▁
wandb:       kl_term_batch ███▁▁▁▃▃▁▁▁▁▁▁▁▂▁▁▁▁▁▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: kl_term_unormalized ███▄▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                  lr ▄▃▂▁█▃▂▁▁▁▇▃▂▁▁▇▄▃▁▆▃▁▁█▁▁▂▁█▇▃▂▁█▇▁▆▅▃▁
wandb:     test_acc_task_0 ██▆▆▅▃▃▁▁▁
wandb:     test_acc_task_1 █▇▆▁▅▁▄▅▅
wandb:     test_acc_task_2 ██▅▄▃▄▁▂
wandb:     test_acc_task_3 █▂▆▇▁▄▅
wandb:     test_acc_task_4 ▇█▇▆▁▂
wandb:     test_acc_task_5 ▇▅█▄▁
wandb:     test_acc_task_6 █▇▅▁
wandb:     test_acc_task_7 █▆▁
wandb:     test_acc_task_8 █▁
wandb:     test_acc_task_9 ▁
wandb:    test_loss_task_0 ▁▁▁▁▁▁▁▁▁▁
wandb:    test_loss_task_1 ▁▁▁▁▁▁▁▁▁
wandb:    test_loss_task_2 ▁▁

>>> Test on task  5 - kmnist-0-1     : loss=-1.000, acc= 97.7% <<<
>>> Test on task  6 - kmnist-2-3     : loss=-1.000, acc= 93.9% <<<
Average accuracy: 68.2%
Save at ./res/smnist/vcl/re_g/93.txt
****************************************************************************************************
Task  7 (kmnist-4-5)
****************************************************************************************************
training for 11 epochs
Total number of steps per task 7: 1856
Scheduling on.
| Epoch   1, time= 17.0ms| Train: class_loss=0.004  kl_loss=0.130 total_loss=0.135, acc= 88.3% |
| Epoch   2, time= 17.1ms| Train: class_loss=0.002  kl_loss=0.009 total_loss=0.011, acc= 96.8% |
| Epoch   3, time= 17.0ms| Train: class_loss=0.002  kl_loss=0.007 total_loss=0.009, acc= 97.6% |
| Epoch   4, time= 17.1ms| Train: class_loss=0.001  kl_loss=0.004 total_loss=0.006, acc= 97.6% |
| Epoch   5, time= 17.1ms| Train: class_loss=0.001  kl_loss=0.004 total_loss=0.005, acc= 97.8% |
| Epoch   6, time= 1

Note that currently gvcl is actually implementing renyi regularization

In [ ]:
import subprocess

# Define the parameters
experiment = "smnist"
approach = "gvcl"
reg_type = "kl_g"
seeds = [1, 23, 47, 61, 93]

# Loop over the seeds and run the experiment
for sd in seeds:
    print(f"Running experiment with seed {sd}")
    subprocess.run([
        "python", "./src/run.py",
        "--use-sweep", "True",
        "--experiment", experiment,
        "--approach", approach,
        "--seed", str(sd),
        "--regularizer", reg_type
    ])

In [ ]:
# Define the parameters
experiment = "cifar"
approach = "gvcl"
reg_type = "kl_g"
seeds = [0, 23, 89, 12]

# Loop over the seeds and run the experiment
for seed in seeds:
    print(f"Running experiment with seed {seed}")
    %run ./src/run.py --experiment $experiment --approach $approach --regularizer $reg_type --seed $seed --train_samples 1

In [ ]:
# Define the parameters
experiment = "cifar"
approach = "gvcl"
reg_type = "kl_g"
seeds = [0, 1, 2, 3]

# Loop over the seeds and run the experiment
for seed in seeds:
    print(f"Running experiment with seed {seed}")
    %run ./src/run.py --experiment $experiment --approach $approach --regularizer $reg_type --seed $seed

In [ ]:
%run ../src/run.py --experiment smnist --approach gvclf --seed 3

In [ ]:
import math

def compute_renyi(alpha, mu0, sigma0, mu1, sigma1):
    """
    Compute the Rényi divergence D_alpha between two normal distributions:
    N(mu0, sigma0^2) and N(mu1, sigma1^2).
    
    Parameters:
    - alpha: The Rényi divergence parameter (alpha > 0, alpha != 1).
    - mu0: Mean of the first distribution.
    - sigma0: Standard deviation of the first distribution.
    - mu1: Mean of the second distribution.
    - sigma1: Standard deviation of the second distribution.
    
    Returns:
    - D_alpha: The Rényi divergence value.
    """
    # Compute sigma^2_alpha
    sigma_alpha_squared = (1 - alpha) * sigma0**2 + alpha * sigma1**2
    if sigma_alpha_squared <= 0:
        raise ValueError("sigma_alpha_squared must be greater than 0.")
    
    # Compute terms of the Rényi divergence
    mean_term = alpha * (mu1 - mu0)**2 / (2 * sigma_alpha_squared)
    log_term = (1 / (1 - alpha)) * math.log(
        (sigma_alpha_squared ** 0.5) / (sigma0 ** (1 - alpha) * sigma1 ** alpha)
    )
    
    # Calculate the Rényi divergence
    D_alpha = mean_term + log_term
    return D_alpha

# Example usage:
alpha = 2.0
mu0 = 0.0
sigma0 = 1.0
mu1 = 1.0
sigma1 = 2.0

result = compute_renyi(alpha, mu0, sigma0, mu1, sigma1)
print(f"Rényi divergence: {result}")


In [ ]:
import torch

def renyi_divergence_univariate_gaussians(mean, log_var, prior_mean, log_prior_var, alpha, sum = True):
    """
    Compute the Rényi divergence between univariate Gaussian posterior and prior distributions.
    
    Args:
        mean (torch.Tensor): Posterior mean (shape: [n]).
        log_var (torch.Tensor): Log-variance of the posterior (shape: [n]).
        prior_mean (torch.Tensor): Prior mean (shape: [n]).
        log_prior_var (torch.Tensor): Log-variance of the prior (shape: [n]).
        alpha (float): Order of the Rényi divergence (alpha > 0, alpha != 1).
    
    Returns:
        torch.Tensor: Rényi divergence for each element in the input tensor (shape: [n]).
    """
    # Compute posterior variance and prior variance from log-variances
    var = torch.exp(log_var)  # Posterior variance
    prior_var = torch.exp(log_prior_var)  # Prior variance

    # Compute the mixed variance (Σ_α)^*
    mixed_var = alpha * prior_var + (1 - alpha) * var

    # Compute the Mahalanobis term: α (μ - μ_prior)^2 / (Σ_α)^*
    mahalanobis_term = alpha * (mean - prior_mean) ** 2 / mixed_var

    # Compute the determinant term: log(|Σ_α^*|) - ((1 - α) log(|Σ|) + α log(|Σ_prior|))
    log_det_term = torch.log(mixed_var) - ((1 - alpha) * log_var + alpha * log_prior_var)

    if sum:
        return 0.5 * torch.sum(mahalanobis_term - 0.5 / (alpha - 1) * log_det_term)
    # Combine terms to compute Rényi divergence
    else:
        return 0.5 * mahalanobis_term - 0.5 / (alpha - 1)

# Example data
mean = torch.tensor([0.5, 0.2, -0.3])
log_var = torch.tensor([-1.0, -0.5, -1.2])
prior_mean = torch.tensor([0.0, 0.0, 0.0])
log_prior_var = torch.tensor([-0.5, -0.5, -0.5])
alpha = 0.5

# Compute Rényi divergence
divergence = renyi_divergence_univariate_gaussians(mean, log_var, prior_mean, log_prior_var, alpha)
print(divergence)



In [ ]:
%run ../src/run.py --experiment easy-chasy --approach hat --seed 0

In [ ]:
%run ../src/run.py --experiment cifar --approach hat

In [ ]:
%run ../src/run.py --experiment cifar --approach gvclf --seed 3

In [ ]:
import torch
print(torch.cuda.is_available())

In [ ]:
%run ../src/run.py --experiment cifar --approach gvclf

In [ ]:
%run ../src/run.py --experiment smnist --approach hat --seed 14

In [ ]:
import matplotlib.pyplot as plt

def calculate_average_accuracy(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
    
    average_accuracies = []
    
    for i, line in enumerate(lines):
        values = list(map(float, line.split()))
        non_zero_values = values[:i+1]
        average_accuracy = sum(non_zero_values) / len(non_zero_values)
        average_accuracies.append(average_accuracy)
        print(f"Row {i+1} average accuracy: {average_accuracy:.4f}")
    
    return average_accuracies

def plot_accuracies(accuracies):
    plt.plot(range(1, len(accuracies) + 1), accuracies, marker='o')
    plt.xlabel('Number of Tasks Learned')
    plt.ylabel('Average Accuracy')
    plt.title('Average Accuracy Across Tasks')
    plt.grid(True)
    plt.show()

# Calculate average accuracies
average_accuracies = calculate_average_accuracy('../res/smnist_gvclf_14.txt')

# Plot the accuracies
plot_accuracies(average_accuracies)

In [ ]:
import matplotlib.pyplot as plt

def calculate_average_accuracy(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
    
    average_accuracies = []
    
    for i, line in enumerate(lines):
        values = list(map(float, line.split()))
        non_zero_values = values[:i+1]
        average_accuracy = sum(non_zero_values) / len(non_zero_values)
        average_accuracies.append(average_accuracy)
        #print(f"Row {i+1} average accuracy: {average_accuracy:.4f}")
    
    return average_accuracies

def plot_accuracies(file_paths):
    for file_path in file_paths:
        accuracies = calculate_average_accuracy(file_path)
        plt.plot(range(1, len(accuracies) + 1), accuracies, marker='o', label=file_path)
    
    plt.xlabel('Number of Tasks Learned')
    plt.ylabel('Average Accuracy')
    plt.title('Average Accuracy Across Tasks')
    plt.legend()
    plt.grid(True)
    plt.show()

# List of result files
result_files = [
    '../res/smnist_gvcl_0.txt',
    '../res/smnist_hat_0.txt',
    '../res/smnist_vcrenyi_3.txt',
]

# Plot the accuracies for each result file
plot_accuracies(result_files)