In [22]:
%load_ext autoreload
%autoreload 2


%run ./src/run.py --help


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
usage: run.py [-h] [--seed SEED] --experiment
              {mnist2,pmnist,cifar,mixture,easy-chasy,hard-chasy,smnist}
              --approach
              {random,sgd,sgd-frozen,lwf,lfl,ewc,imm-mean,progressive,pathnet,imm-mode,sgd-restart,ewc2,ewc-film,joint,hat,hat-test,gvcl,vcl,vclf,gvclf}
              [--regularizer {kl_g,re_g,kl_qg,t_st}] [--q Q] [--v V]
              [--output OUTPUT] [--nepochs NEPOCHS] [--lr LR]
              [--parameter PARAMETER] [--ntasks NTASKS] [--momentum MOMENTUM]
              [--weight_decay WEIGHT_DECAY] [--beta BETA] [--lamb LAMB]
              [--root_path ROOT_PATH]
              [--use-best-hyperparams USE_BEST_HYPERPARAMS]
              [--use-sweep USE_SWEEP] [--train_samples TRAIN_SAMPLES]

xxx

options:
  -h, --help            show this help message and exit
  --seed SEED           (default=0)
  --experiment {mnist2,pmnist,cifar,mixture,easy-chasy,hard

In [ ]:
from best_hyperparams import sweep_params

In [2]:
import torch
print(torch.cuda.is_available())

True


In [33]:

# Test run for the t_st regularizer

experiment = "smnist"
approach = "vcl"
reg_type = "re_g"
q = 2
v = 2
seed = 1  # Only one seed
nepochs = 10  # Set number of epochs to 10
%run ./src/run.py --experiment $experiment --approach $approach --reg_type $reg_type --q $q --v $v --seed $seed --nepochs $nepochs --lr 0.01 --nepochs 10

usage: run.py [-h] [--seed SEED] --experiment
              {mnist2,pmnist,cifar,mixture,easy-chasy,hard-chasy,smnist}
              --approach
              {random,sgd,sgd-frozen,lwf,lfl,ewc,imm-mean,progressive,pathnet,imm-mode,sgd-restart,ewc2,ewc-film,joint,hat,hat-test,gvcl,vcl,vclf,gvclf}
              [--reg_type {kl_g,re_g,kl_qg,t_st}] [--q Q] [--v V]
              [--output OUTPUT] [--nepochs NEPOCHS] [--lr LR]
              [--parameter PARAMETER] [--ntasks NTASKS] [--momentum MOMENTUM]
              [--weight_decay WEIGHT_DECAY] [--beta BETA] [--lamb LAMB]
              [--root_path ROOT_PATH]
              [--use-best-hyperparams USE_BEST_HYPERPARAMS]
              [--use-sweep USE_SWEEP] [--train_samples TRAIN_SAMPLES]
run.py: error: unrecognized arguments: --regularizer re_g


SystemExit: 2

In [2]:
%run ./src/run.py --use-sweep True --experiment smnist --approach gvcl --seed 42 --reg_type kl_g

Arguments =
	seed: 42
	experiment: smnist
	approach: gvcl
	reg_type: kl_g
	q: 1.01
	v: 1
	output: ./res/smnist_gvcl_kl_g_1.01_1_42.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: False
	use_sweep: True
	train_samples: 10
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([1, 1, 1,  ..., 0, 1, 1])
tensor([1, 0, 1,  ..., 0, 1, 0])
tensor([1, 1, 1,  ..., 1, 1, 1])
tensor([1, 0, 0,  ..., 1, 1, 1])
tensor([1, 1, 1,  ..., 1, 1, 1])
tensor([1, 0, 0,  ..., 1, 0, 0])
tensor([0, 1, 0,  ..., 1, 0, 0])
tensor([1, 1, 1,  ..., 1, 1, 0])
tensor([0, 1, 1,  ..., 1, 0, 1])
tensor([0, 1, 1,  ..., 0, 1, 0])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1, 2), (2, 2), (3, 2), (4, 2), (5, 2), (6, 2), (7, 2), (8, 2), (9, 2)]
Inits...
Film type none
----------

KeyboardInterrupt: 

In [12]:
import subprocess

# Define the parameters
experiment = "smnist"
approach = "vcl"
reg_type = "re_g"
q = 1.02
seeds = [1, 23, 47, 61, 93]

# Loop over the seeds and run the experiment
for sd in seeds:
    print(f"Running experiment with seed {sd}")
    subprocess.run([
        "python", "./src/run.py",
        "--experiment", experiment,
        "--approach", approach,
        "--q", str(q),
        "--seed", str(sd),
        "--use-best-hyperparams", str(True),
        "--regularizer", reg_type
    ])

Running experiment with seed 1


wandb: Currently logged in as: naima-elosegui (nagiu). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.3
wandb: Run data is saved locally in /home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/wandb/run-20250119_021330-kedhcoxl
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run vital-jazz-455
wandb: ⭐️ View project at https://wandb.ai/nagiu/curvy-cl
wandb: 🚀 View run at https://wandb.ai/nagiu/curvy-cl/runs/kedhcoxl


Arguments =
	seed: 1
	experiment: smnist
	approach: vcl
	regularizer: re_g
	q: 1.02
	output: ./res/smnist/vcl/re_g/smnist_vcl_re_g_1.02_1.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: True
	use_sweep: False
	train_samples: 10
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([0, 1, 0,  ..., 1, 1, 1])
tensor([1, 0, 0,  ..., 1, 1, 1])
tensor([0, 0, 1,  ..., 0, 1, 1])
tensor([0, 0, 0,  ..., 0, 1, 1])
tensor([1, 0, 0,  ..., 0, 1, 1])
tensor([0, 1, 0,  ..., 1, 0, 0])
tensor([0, 1, 1,  ..., 0, 0, 1])
tensor([0, 0, 0,  ..., 0, 1, 1])
tensor([1, 0, 1,  ..., 1, 1, 1])
tensor([1, 1, 1,  ..., 0, 0, 1])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1, 2), (2, 2), (3, 2), (4, 2), (5, 2), (6, 2), (7, 2), (8, 2), (9, 2)]
Inits...
Film type none
---

wandb: Currently logged in as: naima-elosegui (nagiu). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.3
wandb: Run data is saved locally in /home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/wandb/run-20250119_024326-1vj2b5q2
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run brisk-sea-456
wandb: ⭐️ View project at https://wandb.ai/nagiu/curvy-cl
wandb: 🚀 View run at https://wandb.ai/nagiu/curvy-cl/runs/1vj2b5q2


Arguments =
	seed: 23
	experiment: smnist
	approach: vcl
	regularizer: re_g
	q: 1.02
	output: ./res/smnist/vcl/re_g/smnist_vcl_re_g_1.02_23.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: True
	use_sweep: False
	train_samples: 10
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([1, 0, 1,  ..., 0, 1, 0])
tensor([0, 1, 1,  ..., 0, 0, 1])
tensor([1, 0, 1,  ..., 0, 1, 1])
tensor([0, 1, 0,  ..., 1, 0, 1])
tensor([1, 1, 1,  ..., 0, 0, 0])
tensor([1, 0, 0,  ..., 1, 1, 0])
tensor([1, 0, 1,  ..., 0, 0, 1])
tensor([0, 0, 0,  ..., 0, 0, 0])
tensor([0, 0, 0,  ..., 1, 0, 0])
tensor([0, 1, 0,  ..., 0, 0, 0])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1, 2), (2, 2), (3, 2), (4, 2), (5, 2), (6, 2), (7, 2), (8, 2), (9, 2)]
Inits...
Film type none
-

wandb: Currently logged in as: naima-elosegui (nagiu). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.3
wandb: Run data is saved locally in /home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/wandb/run-20250119_031310-8fmyoxl8
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run ethereal-pyramid-457
wandb: ⭐️ View project at https://wandb.ai/nagiu/curvy-cl
wandb: 🚀 View run at https://wandb.ai/nagiu/curvy-cl/runs/8fmyoxl8


Arguments =
	seed: 47
	experiment: smnist
	approach: vcl
	regularizer: re_g
	q: 1.02
	output: ./res/smnist/vcl/re_g/smnist_vcl_re_g_1.02_47.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: True
	use_sweep: False
	train_samples: 10
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([0, 1, 1,  ..., 1, 1, 1])
tensor([1, 0, 0,  ..., 0, 0, 1])
tensor([0, 1, 1,  ..., 0, 0, 0])
tensor([1, 1, 0,  ..., 0, 1, 1])
tensor([0, 1, 1,  ..., 0, 0, 1])
tensor([1, 1, 1,  ..., 1, 0, 1])
tensor([1, 1, 1,  ..., 1, 0, 1])
tensor([1, 0, 1,  ..., 0, 1, 1])
tensor([0, 1, 1,  ..., 0, 0, 1])
tensor([1, 1, 1,  ..., 0, 1, 0])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1, 2), (2, 2), (3, 2), (4, 2), (5, 2), (6, 2), (7, 2), (8, 2), (9, 2)]
Inits...
Film type none
-

wandb: Currently logged in as: naima-elosegui (nagiu). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.3
wandb: Run data is saved locally in /home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/wandb/run-20250119_034253-tp3j1c93
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run rose-energy-458
wandb: ⭐️ View project at https://wandb.ai/nagiu/curvy-cl
wandb: 🚀 View run at https://wandb.ai/nagiu/curvy-cl/runs/tp3j1c93


Arguments =
	seed: 61
	experiment: smnist
	approach: vcl
	regularizer: re_g
	q: 1.02
	output: ./res/smnist/vcl/re_g/smnist_vcl_re_g_1.02_61.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: True
	use_sweep: False
	train_samples: 10
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([0, 0, 1,  ..., 1, 0, 1])
tensor([0, 1, 0,  ..., 1, 1, 1])
tensor([0, 0, 1,  ..., 0, 1, 0])
tensor([0, 1, 1,  ..., 0, 0, 1])
tensor([1, 1, 1,  ..., 0, 0, 0])
tensor([1, 1, 1,  ..., 0, 0, 1])
tensor([0, 1, 0,  ..., 1, 0, 1])
tensor([0, 1, 0,  ..., 0, 0, 1])
tensor([1, 1, 0,  ..., 1, 1, 0])
tensor([0, 0, 0,  ..., 0, 1, 0])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1, 2), (2, 2), (3, 2), (4, 2), (5, 2), (6, 2), (7, 2), (8, 2), (9, 2)]
Inits...
Film type none
-

wandb: Currently logged in as: naima-elosegui (nagiu). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.3
wandb: Run data is saved locally in /home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/wandb/run-20250119_041233-vf9vhgoj
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run balmy-voice-459
wandb: ⭐️ View project at https://wandb.ai/nagiu/curvy-cl
wandb: 🚀 View run at https://wandb.ai/nagiu/curvy-cl/runs/vf9vhgoj


Arguments =
	seed: 93
	experiment: smnist
	approach: vcl
	regularizer: re_g
	q: 1.02
	output: ./res/smnist/vcl/re_g/smnist_vcl_re_g_1.02_93.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: True
	use_sweep: False
	train_samples: 10
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([1, 0, 0,  ..., 0, 0, 0])
tensor([0, 0, 0,  ..., 1, 0, 1])
tensor([0, 0, 0,  ..., 1, 1, 1])
tensor([1, 1, 1,  ..., 0, 1, 1])
tensor([0, 0, 0,  ..., 0, 1, 1])
tensor([1, 1, 0,  ..., 0, 0, 0])
tensor([1, 1, 1,  ..., 1, 0, 0])
tensor([0, 0, 0,  ..., 0, 1, 0])
tensor([1, 0, 1,  ..., 0, 0, 0])
tensor([1, 1, 0,  ..., 1, 1, 0])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1, 2), (2, 2), (3, 2), (4, 2), (5, 2), (6, 2), (7, 2), (8, 2), (9, 2)]
Inits...
Film type none
-

In [3]:
import subprocess

# Define the parameters
experiment = "smnist"
approach = "vcl"
reg_type = "re_g"
q = [1.5]
seeds = [61,93]

# Loop over the seeds and run the experiment
for curv in q: 
    for sd in seeds:
        print(f"Running experiment with seed {sd}")
        subprocess.run([
            "python", "./src/run.py",
            "--experiment", experiment,
            "--approach", approach,
            "--q", str(curv),
            "--seed", str(sd),
            "--use-best-hyperparams", str(True),
            "--regularizer", reg_type
        ])

Running experiment with seed 61


wandb: Currently logged in as: naima-elosegui (nagiu). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.3
wandb: Run data is saved locally in /home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/wandb/run-20250119_204022-6zwk2uxv
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run sandy-smoke-503
wandb: ⭐️ View project at https://wandb.ai/nagiu/curvy-cl
wandb: 🚀 View run at https://wandb.ai/nagiu/curvy-cl/runs/6zwk2uxv


Arguments =
	seed: 61
	experiment: smnist
	approach: vcl
	regularizer: re_g
	q: 1.5
	output: ./res/smnist/vcl/re_g/smnist_vcl_re_g_1.5_61.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: True
	use_sweep: False
	train_samples: 10
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([0, 0, 1,  ..., 1, 0, 1])
tensor([0, 1, 0,  ..., 1, 1, 1])
tensor([0, 0, 1,  ..., 0, 1, 0])
tensor([0, 1, 1,  ..., 0, 0, 1])
tensor([1, 1, 1,  ..., 0, 0, 0])
tensor([1, 1, 1,  ..., 0, 0, 1])
tensor([0, 1, 0,  ..., 1, 0, 1])
tensor([0, 1, 0,  ..., 0, 0, 1])
tensor([1, 1, 0,  ..., 1, 1, 0])
tensor([0, 0, 0,  ..., 0, 1, 0])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1, 2), (2, 2), (3, 2), (4, 2), (5, 2), (6, 2), (7, 2), (8, 2), (9, 2)]
Inits...
Film type none
---

wandb: Currently logged in as: naima-elosegui (nagiu). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.19.3
wandb: Run data is saved locally in /home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/wandb/run-20250119_210945-pbfawmiz
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run lyric-frog-504
wandb: ⭐️ View project at https://wandb.ai/nagiu/curvy-cl
wandb: 🚀 View run at https://wandb.ai/nagiu/curvy-cl/runs/pbfawmiz


Arguments =
	seed: 93
	experiment: smnist
	approach: vcl
	regularizer: re_g
	q: 1.5
	output: ./res/smnist/vcl/re_g/smnist_vcl_re_g_1.5_93.txt
	nepochs: -1
	lr: -1
	parameter: 
	ntasks: -1
	momentum: 0.9
	weight_decay: 0.0001
	beta: 1
	lamb: 1
	root_path: ./
	use_best_hyperparams: True
	use_sweep: False
	train_samples: 10
approach VCL True
using vcl model smnist
Load data...
./dat/
Task 0 loaded
Task 1 loaded
Task 2 loaded
Task 3 loaded
Task 4 loaded
Task 5 loaded
Task 6 loaded
Task 7 loaded
Task 8 loaded
Task 9 loaded
tensor([1, 0, 0,  ..., 0, 0, 0])
tensor([0, 0, 0,  ..., 1, 0, 1])
tensor([0, 0, 0,  ..., 1, 1, 1])
tensor([1, 1, 1,  ..., 0, 1, 1])
tensor([0, 0, 0,  ..., 0, 1, 1])
tensor([1, 1, 0,  ..., 0, 0, 0])
tensor([1, 1, 1,  ..., 1, 0, 0])
tensor([0, 0, 0,  ..., 0, 1, 0])
tensor([1, 0, 1,  ..., 0, 0, 0])
tensor([1, 1, 0,  ..., 1, 1, 0])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1, 2), (2, 2), (3, 2), (4, 2), (5, 2), (6, 2), (7, 2), (8, 2), (9, 2)]
Inits...
Film type none
---

Note that currently gvcl is actually implementing renyi regularization

In [6]:
import subprocess

# Define the parameters
experiment = "smnist"
approach = "gvcl"
reg_type = "kl_g"
seeds = [1, 23, 47, 61, 93]

# Loop over the seeds and run the experiment
for sd in seeds:
    print(f"Running experiment with seed {sd}")
    subprocess.run([
        "python", "./src/run.py",
        "--use-sweep", "True",
        "--experiment", experiment,
        "--approach", approach,
        "--seed", str(sd),
        "--regularizer", reg_type
    ])

Running experiment with seed 1


In [ ]:
# Define the parameters
experiment = "cifar"
approach = "gvcl"
reg_type = "kl_g"
seeds = [0, 23, 89, 12]

# Loop over the seeds and run the experiment
for seed in seeds:
    print(f"Running experiment with seed {seed}")
    %run ./src/run.py --experiment $experiment --approach $approach --regularizer $reg_type --seed $seed --train_samples 1

In [ ]:
# Define the parameters
experiment = "cifar"
approach = "gvcl"
reg_type = "kl_g"
seeds = [0, 1, 2, 3]

# Loop over the seeds and run the experiment
for seed in seeds:
    print(f"Running experiment with seed {seed}")
    %run ./src/run.py --experiment $experiment --approach $approach --regularizer $reg_type --seed $seed

In [ ]:
%run ../src/run.py --experiment smnist --approach gvclf --seed 3

In [ ]:
import math

def compute_renyi(alpha, mu0, sigma0, mu1, sigma1):
    """
    Compute the Rényi divergence D_alpha between two normal distributions:
    N(mu0, sigma0^2) and N(mu1, sigma1^2).
    
    Parameters:
    - alpha: The Rényi divergence parameter (alpha > 0, alpha != 1).
    - mu0: Mean of the first distribution.
    - sigma0: Standard deviation of the first distribution.
    - mu1: Mean of the second distribution.
    - sigma1: Standard deviation of the second distribution.
    
    Returns:
    - D_alpha: The Rényi divergence value.
    """
    # Compute sigma^2_alpha
    sigma_alpha_squared = (1 - alpha) * sigma0**2 + alpha * sigma1**2
    if sigma_alpha_squared <= 0:
        raise ValueError("sigma_alpha_squared must be greater than 0.")
    
    # Compute terms of the Rényi divergence
    mean_term = alpha * (mu1 - mu0)**2 / (2 * sigma_alpha_squared)
    log_term = (1 / (1 - alpha)) * math.log(
        (sigma_alpha_squared ** 0.5) / (sigma0 ** (1 - alpha) * sigma1 ** alpha)
    )
    
    # Calculate the Rényi divergence
    D_alpha = mean_term + log_term
    return D_alpha

# Example usage:
alpha = 2.0
mu0 = 0.0
sigma0 = 1.0
mu1 = 1.0
sigma1 = 2.0

result = compute_renyi(alpha, mu0, sigma0, mu1, sigma1)
print(f"Rényi divergence: {result}")


In [ ]:
import torch

def renyi_divergence_univariate_gaussians(mean, log_var, prior_mean, log_prior_var, alpha, sum = True):
    """
    Compute the Rényi divergence between univariate Gaussian posterior and prior distributions.
    
    Args:
        mean (torch.Tensor): Posterior mean (shape: [n]).
        log_var (torch.Tensor): Log-variance of the posterior (shape: [n]).
        prior_mean (torch.Tensor): Prior mean (shape: [n]).
        log_prior_var (torch.Tensor): Log-variance of the prior (shape: [n]).
        alpha (float): Order of the Rényi divergence (alpha > 0, alpha != 1).
    
    Returns:
        torch.Tensor: Rényi divergence for each element in the input tensor (shape: [n]).
    """
    # Compute posterior variance and prior variance from log-variances
    var = torch.exp(log_var)  # Posterior variance
    prior_var = torch.exp(log_prior_var)  # Prior variance

    # Compute the mixed variance (Σ_α)^*
    mixed_var = alpha * prior_var + (1 - alpha) * var

    # Compute the Mahalanobis term: α (μ - μ_prior)^2 / (Σ_α)^*
    mahalanobis_term = alpha * (mean - prior_mean) ** 2 / mixed_var

    # Compute the determinant term: log(|Σ_α^*|) - ((1 - α) log(|Σ|) + α log(|Σ_prior|))
    log_det_term = torch.log(mixed_var) - ((1 - alpha) * log_var + alpha * log_prior_var)

    if sum:
        return 0.5 * torch.sum(mahalanobis_term - 0.5 / (alpha - 1) * log_det_term)
    # Combine terms to compute Rényi divergence
    else:
        return 0.5 * mahalanobis_term - 0.5 / (alpha - 1)

# Example data
mean = torch.tensor([0.5, 0.2, -0.3])
log_var = torch.tensor([-1.0, -0.5, -1.2])
prior_mean = torch.tensor([0.0, 0.0, 0.0])
log_prior_var = torch.tensor([-0.5, -0.5, -0.5])
alpha = 0.5

# Compute Rényi divergence
divergence = renyi_divergence_univariate_gaussians(mean, log_var, prior_mean, log_prior_var, alpha)
print(divergence)



In [ ]:
%run ../src/run.py --experiment easy-chasy --approach hat --seed 0

In [ ]:
%run ../src/run.py --experiment cifar --approach hat

In [ ]:
%run ../src/run.py --experiment cifar --approach gvclf --seed 3

In [ ]:
import torch
print(torch.cuda.is_available())

In [ ]:
%run ../src/run.py --experiment cifar --approach gvclf

In [ ]:
%run ../src/run.py --experiment smnist --approach hat --seed 14

In [ ]:
import matplotlib.pyplot as plt

def calculate_average_accuracy(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
    
    average_accuracies = []
    
    for i, line in enumerate(lines):
        values = list(map(float, line.split()))
        non_zero_values = values[:i+1]
        average_accuracy = sum(non_zero_values) / len(non_zero_values)
        average_accuracies.append(average_accuracy)
        print(f"Row {i+1} average accuracy: {average_accuracy:.4f}")
    
    return average_accuracies

def plot_accuracies(accuracies):
    plt.plot(range(1, len(accuracies) + 1), accuracies, marker='o')
    plt.xlabel('Number of Tasks Learned')
    plt.ylabel('Average Accuracy')
    plt.title('Average Accuracy Across Tasks')
    plt.grid(True)
    plt.show()

# Calculate average accuracies
average_accuracies = calculate_average_accuracy('../res/smnist_gvclf_14.txt')

# Plot the accuracies
plot_accuracies(average_accuracies)

In [ ]:
import matplotlib.pyplot as plt

def calculate_average_accuracy(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
    
    average_accuracies = []
    
    for i, line in enumerate(lines):
        values = list(map(float, line.split()))
        non_zero_values = values[:i+1]
        average_accuracy = sum(non_zero_values) / len(non_zero_values)
        average_accuracies.append(average_accuracy)
        #print(f"Row {i+1} average accuracy: {average_accuracy:.4f}")
    
    return average_accuracies

def plot_accuracies(file_paths):
    for file_path in file_paths:
        accuracies = calculate_average_accuracy(file_path)
        plt.plot(range(1, len(accuracies) + 1), accuracies, marker='o', label=file_path)
    
    plt.xlabel('Number of Tasks Learned')
    plt.ylabel('Average Accuracy')
    plt.title('Average Accuracy Across Tasks')
    plt.legend()
    plt.grid(True)
    plt.show()

# List of result files
result_files = [
    '../res/smnist_gvcl_0.txt',
    '../res/smnist_hat_0.txt',
    '../res/smnist_vcrenyi_3.txt',
]

# Plot the accuracies for each result file
plot_accuracies(result_files)