In [1]:
%load_ext autoreload
%autoreload 2


%run ../src/run.py --help


usage: run.py [-h] [--seed SEED] --experiment
              {mnist2,pmnist,cifar,mixture,easy-chasy,hard-chasy,smnist}
              --approach
              {random,sgd,sgd-frozen,lwf,lfl,ewc,imm-mean,progressive,pathnet,imm-mode,sgd-restart,ewc2,ewc-film,joint,hat,hat-test,gvcl,vcl,vclf,gvclf}
              [--output OUTPUT] [--nepochs NEPOCHS] [--lr LR]
              [--parameter PARAMETER] [--ntasks NTASKS]
              [--use-best-hyperparams USE_BEST_HYPERPARAMS]

xxx

options:
  -h, --help            show this help message and exit
  --seed SEED           (default=0)
  --experiment {mnist2,pmnist,cifar,mixture,easy-chasy,hard-chasy,smnist}
                        (default=)
  --approach {random,sgd,sgd-frozen,lwf,lfl,ewc,imm-mean,progressive,pathnet,imm-mode,sgd-restart,ewc2,ewc-film,joint,hat,hat-test,gvcl,vcl,vclf,gvclf}
                        (default=)
  --output OUTPUT       (default=)
  --nepochs NEPOCHS     (default=200)
  --lr LR               (default=0.050000)
  --pa

In [7]:
%run ../src/dataloaders/hasy_utils.py

copying


In [20]:
%run ../src/run.py --experiment smnist --approach gvcl

Arguments =
	seed: 0
	experiment: smnist
	approach: gvcl
	output: ../res/smnist_gvcl_0.txt
	nepochs: 200
	lr: 0.05
	parameter: 
	ntasks: -1
	use_best_hyperparams: True
Load data...
Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 9912422/9912422 [00:00<00:00, 11116684.62it/s]


Extracting ../dat/MNIST/raw/train-images-idx3-ubyte.gz to ../dat/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 28881/28881 [00:00<00:00, 299331.81it/s]


Extracting ../dat/MNIST/raw/train-labels-idx1-ubyte.gz to ../dat/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 1648877/1648877 [00:00<00:00, 2795618.86it/s]


Extracting ../dat/MNIST/raw/t10k-images-idx3-ubyte.gz to ../dat/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 4542/4542 [00:00<00:00, 5370884.91it/s]


Extracting ../dat/MNIST/raw/t10k-labels-idx1-ubyte.gz to ../dat/MNIST/raw



100%|██████████| 18165135/18165135 [00:15<00:00, 1152334.65it/s]


Extracting ../dat/KMNIST/raw/train-images-idx3-ubyte.gz to ../dat/KMNIST/raw



100%|██████████| 29497/29497 [00:00<00:00, 124188.57it/s]


Extracting ../dat/KMNIST/raw/train-labels-idx1-ubyte.gz to ../dat/KMNIST/raw



100%|██████████| 3041136/3041136 [00:04<00:00, 749043.23it/s]


Extracting ../dat/KMNIST/raw/t10k-images-idx3-ubyte.gz to ../dat/KMNIST/raw



100%|██████████| 5120/5120 [00:00<00:00, 4013237.99it/s]


Extracting ../dat/KMNIST/raw/t10k-labels-idx1-ubyte.gz to ../dat/KMNIST/raw

SLDKJFLSDJL
SLDKJFLSDJL
SLDKJFLSDJL
SLDKJFLSDJL
SLDKJFLSDJL
SLDKJFLSDJL
SLDKJFLSDJL
SLDKJFLSDJL
SLDKJFLSDJL
SLDKJFLSDJL
tensor([1, 0, 1,  ..., 1, 1, 1])
tensor([1, 0, 0,  ..., 0, 0, 1])
tensor([0, 0, 0,  ..., 0, 1, 0])
tensor([0, 0, 0,  ..., 1, 0, 0])
tensor([1, 0, 1,  ..., 0, 1, 1])
tensor([1, 0, 1,  ..., 1, 0, 0])
tensor([0, 1, 0,  ..., 0, 1, 1])
tensor([0, 1, 0,  ..., 1, 0, 1])
tensor([0, 1, 1,  ..., 1, 0, 0])
tensor([0, 1, 0,  ..., 1, 0, 1])
Input size = [1, 28, 28] 
Task info = [(0, 2), (1, 2), (2, 2), (3, 2), (4, 2), (5, 2), (6, 2), (7, 2), (8, 2), (9, 2)]
Inits...
point
----------------------------------------------------------------------------------------------------
Net(
  (conv_layers): ModuleList()
  (fc_layers): ModuleList(
    (0-1): 2 x MFLinearLayer()
  )
  (heads): ModuleList(
    (0-9): 10 x MFLinearLayer()
  )
  (conv_film_layers): ModuleList()
  (fc_film_layers): ModuleList(
    (0-1): 2 x 

/home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/src/approaches/gvcl.py:135: FutureWarning: `torch.nn.utils.clip_grad_norm` is now deprecated in favor of `torch.nn.utils.clip_grad_norm_`.
  torch.nn.utils.clip_grad_norm(self.model.parameters(),self.clipgrad)


| Epoch   1, time= 13.0ms| Train: class_loss=0.037  kl_loss=0.041  total_loss=0.077, acc= 98.8% |
| Epoch   2, time=  8.2ms| Train: class_loss=0.025  kl_loss=0.008  total_loss=0.033, acc= 99.8% |
| Epoch   3, time=  8.2ms| Train: class_loss=0.031  kl_loss=0.008  total_loss=0.039, acc= 99.8% |
| Epoch   4, time=  8.2ms| Train: class_loss=0.058  kl_loss=0.009  total_loss=0.067, acc= 99.8% |
| Epoch   5, time=  8.2ms| Train: class_loss=0.003  kl_loss=0.008  total_loss=0.011, acc=100.0% |
| Epoch   6, time=  8.2ms| Train: class_loss=0.001  kl_loss=0.007  total_loss=0.008, acc=100.0% |
| Epoch   7, time=  8.0ms| Train: class_loss=0.107  kl_loss=0.008  total_loss=0.115, acc= 99.9% |
| Epoch   8, time=  8.1ms| Train: class_loss=0.237  kl_loss=0.012  total_loss=0.249, acc= 99.8% |
| Epoch   9, time=  8.1ms| Train: class_loss=0.412  kl_loss=0.016  total_loss=0.428, acc= 99.9% |
| Epoch  10, time=  8.2ms| Train: class_loss=0.122  kl_loss=0.016  total_loss=0.138, acc= 99.9% |
| Epoch  11, time=  

/home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/src/approaches/gvcl.py:158: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  images=torch.autograd.Variable(x[b],volatile=True)
/home/nelosegui/BIFOLD_work/CL_curved/gvcl_fork/src/approaches/gvcl.py:159: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  targets=torch.autograd.Variable(y[b],volatile=True)


| Epoch   1, time=  8.1ms| Train: class_loss=0.162  kl_loss=0.090  total_loss=0.252, acc= 91.7% |
| Epoch   2, time=  8.0ms| Train: class_loss=0.002  kl_loss=0.030  total_loss=0.032, acc= 96.5% |
| Epoch   3, time=  8.0ms| Train: class_loss=0.012  kl_loss=0.021  total_loss=0.033, acc= 96.7% |
| Epoch   4, time=  8.0ms| Train: class_loss=0.042  kl_loss=0.023  total_loss=0.064, acc= 96.0% |
| Epoch   5, time=  8.1ms| Train: class_loss=0.002  kl_loss=0.020  total_loss=0.021, acc= 97.9% |
| Epoch   6, time=  8.2ms| Train: class_loss=0.001  kl_loss=0.016  total_loss=0.017, acc= 98.1% |
| Epoch   7, time=  8.2ms| Train: class_loss=0.001  kl_loss=0.013  total_loss=0.014, acc= 98.3% |
| Epoch   8, time=  8.2ms| Train: class_loss=0.001  kl_loss=0.012  total_loss=0.013, acc= 98.2% |
| Epoch   9, time=  8.2ms| Train: class_loss=0.001  kl_loss=0.011  total_loss=0.012, acc= 98.5% |
| Epoch  10, time=  8.2ms| Train: class_loss=0.002  kl_loss=0.009  total_loss=0.012, acc= 98.5% |
| Epoch  11, time=  